"""Generate and write entries for books 81-90."""
import json, os
from datetime import datetime

entries = [
    {"filename": "The Austrian Mind An Intellectual and Social History, 1848-1938 (William M. Johnston) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Austrian Mind: An Intellectual and Social History, 1848-1938", "author": "William M. Johnston", "year": 1972, "language": "英文", "publisher": "University of California Press", "description": "William M. Johnston的《奥地利精神：1848-1938年思想与社会史》是一部百科全书式的哈布斯堡帝国思想史巨著，1972年由加州大学出版社出版（xv+515页）。Johnston以令人惊叹的广度跨越了从音乐到医学、从语言学到法学理论的众多学科领域，收录了约70篇知识分子传记，不限于维也纳的德语文化圈，还延伸到匈牙利的布达佩斯与港口的里雅斯特等多元思想场域。Johnston的核心论点是：哈布斯堡思想家们共享两种独特品质——他们是「现代自我知识的奠基者」，同时展现出强烈的整体论思维（holistic thinking）冲动。该书的学术贡献不在于原创性论点，而在于其无与伦比的综合广度与文献指引价值——详尽的注释（pp. 405-472）、分类书目（pp. 475-494）构成了进一步研究的不可或缺的工具。评论界自出版之初即预言其将成为「标准参考书」——「很少有著作能让人从一开始就可以说它将成为标准参考书」。尽管该书对捷克文化几乎完全忽略（雅纳切克、穆哈、马萨里克仅一笔带过），且史学编纂方面也存在显著空白，但其作为哈布斯堡思想史领域学术基础设施建设者的地位无可争议。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Austro-Hungarian Red Book.pdf", "title": "The Austro-Hungarian Red Book", "author": "Austro-Hungarian Ministry of Foreign Affairs (official publication)", "year": 1915, "language": "英文", "publisher": "Oxford University Press (English edition, ed. James Brown Scott)", "description": "《奥匈帝国红皮书》是奥匈帝国外交部于1914-1915年发布的官方外交文件汇编，为第一次世界大战起源研究的最重要一手史料之一。作为各交战国「彩虹书」系列（包括德国白皮书、英国蓝皮书、法国黄皮书、俄国橙皮书、塞尔维亚蓝皮书与比利时灰皮书）的奥匈版本，其英文译本由James Brown Scott编辑，牛津大学出版社出版。全书分三部分组织1914年6月28日（萨拉热窝刺杀）至8月24日期间的外交文件，另有一卷覆盖至1915年5月的对意大利关系。核心文件包括：驻贝尔格莱德使馆关于塞尔维亚公众对刺杀事件反应的报告（文件1-6号）、7月23日对塞尔维亚的最后通牒全文（第7号）、贝希托尔德外相向各国大使发出的说明通牒理由的通函（第8号）、俄国要求延长48小时通牒期限的紧急请求与奥匈帝国的坚决拒绝（第20-21号）、塞尔维亚答复全文及其被奥匈逐条驳斥的论证（第三部分）、以及从俄国局部动员（7月29日）到总动员（7月31日）的升级性外交函电。红皮书的冗长引言系统阐述了帝国的官方战争辩护逻辑——塞尔维亚自卡拉乔尔杰维奇王朝以来系统推行「大塞尔维亚」宣传与革命阴谋、贝尔格莱德政府违背了1909年兼并危机后关于保持友好关系的庄严承诺、协约国因支持『负有罪责的塞尔维亚王国』而必须在历史面前对大战的『不可估量的苦难』负责。作为政府宣传品，该文件必须被批判性地阅读，但其作为维也纳视角下七月危机决策过程的一手文献价值不可替代。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Czechs and the Lands of the Bohemian Crown (Hugh LeCaine Agnew) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Czechs and the Lands of the Bohemian Crown", "author": "Hugh LeCaine Agnew", "year": 2004, "language": "英文", "publisher": "Hoover Institution Press", "description": "Hugh LeCaine Agnew（乔治·华盛顿大学历史学教授）的《捷克人与波希米亚王冠领地》是英语学界最权威的捷克通史单卷本著作，2004年由斯坦福大学胡佛研究所出版社出版于「民族研究」丛书（xxviii+441页，附插图和地图）。全书以16章的结构横跨从前史与早期斯拉夫人定居到捷克共和国加入欧盟的超长时段，将政治-外交史、社会-经济史与文化-思想史三重维度有机结合，吸收了西方学术传统、马克思主义史学与最新一代捷克历史学家的研究成果。在哈布斯堡相关章节中（第4章「异端的王国」覆盖胡斯战争至白山战役的宗教与政治动荡、第9章「合力共济/Viribus Unitis」覆盖1848年至世纪末的帝国框架内捷克民族运动、第10章「世纪末与帝国的终结」聚焦一战与独立），Agnew尤其关注波希米亚在哈布斯堡帝国内部的政治地位演变、捷克民族复兴运动的文化政治逻辑、以及捷克斯洛伐克建国进程中波希米亚历史叙事的核心作用。Wayne S. Vucinich作序，附有详尽书目（pp. 379-413）。该书虽以通史定位，其对哈布斯堡治下捷克经验的综合论述使之成为本馆藏中不可或缺的波希米亚史基础参考文献。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。书名、作者、年份依赖文件名解析与网页搜索。Hoover Institution Press 2004年出版。EPUB元数据需人工核对。", "priority_tier": "standard"},
    {"filename": "The First World War and the End of the Habsburg Monarchy, 1914-1918 (2013) (Manfried Rauchensteiner, Alex J. Kay (tr.) etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The First World War and the End of the Habsburg Monarchy, 1914-1918", "author": "Manfried Rauchensteiner; translated by Alex J. Kay and Anna Güttel-Bellert", "year": 2014, "language": "英文", "publisher": "Böhlau Wien", "description": "Manfried Rauchensteiner的《第一次世界大战与哈布斯堡君主国的终结，1914-1918》是奥地利学界关于哈布斯堡帝国一战经验的权威标准著作，原德文版2013年由Böhlau出版（Der Erste Weltkrieg und das Ende der Habsburgermonarchie 1914-1918），英文译本由Alex J. Kay与Anna Güttel-Bellert翻译、2014年出版（2021年推出修订扩充精装版，总计1181页）。Rauchensteiner系维也纳大学历史学教授、奥地利军事史领域泰斗，曾任奥地利军事博物馆馆长。全书基于数十年的研究积累，系统分析了战争如何从萨拉热窝刺杀后变得不可避免、弗朗茨·约瑟夫皇帝在冲突中的角色、奥匈军队在各条战线上（特别是东线与意大利战线）的军事表现、帝国内部各民族对战争的不同反应、以及640年哈布斯堡王朝如何在1918年因军事失败、民族自决运动与内部合法性崩溃的三重作用下最终解体。该书在奥地利学界被公认为超越了此前所有一战奥匈军事史的标准参考书——其不仅在军事-外交传统框架内提供了最详尽的叙述，还特别关注了战争对平民社会、民族关系与帝国体制合法性侵蚀的多维影响。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The First World War. Germany and Austria-Hungary 1914–1918 (Holger H. Herwig) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The First World War: Germany and Austria-Hungary 1914-1918", "author": "Holger H. Herwig", "year": 1997, "language": "英文", "publisher": "Arnold (Hodder Headline)", "description": "Holger H. Herwig（卡尔加里大学历史学教授）的《第一次世界大战：德国与奥匈帝国，1914-1918》是英语学界唯一一部从德奥同盟国视角全面覆盖一战军事-外交史的综合性著作，1997年由Arnold出版社出版（xix+490页，属Hew Strachan主编的「现代战争」丛书）。Herwig基于1990年德国统一后方才获得的大量此前被封锁的东德档案材料，以及弗赖堡联邦军事档案馆与维也纳国家档案馆的广泛研究，系统挑战了传统英美一战史学中以西线为中心、以德国为主要责任方的叙事框架。该书的核心论点是：同盟国输掉战争的首要原因在于「无能的将领对不足资源的错误管理」——Herwig将特别的批评矛头指向奥匈帝国：「在最初的十二个月内就自我粉碎了」，第一年即损失近百万兵力，此后成为需要德国持续「输血」的战略负担，却拒绝将自己从属于更强大的盟友。经济管理方面，德国与奥匈均未能有效养活其人口或动员经济。Herwig还挑战了德国军事威力的神话，论证德国并不比其对手更适合20世纪的工业化战争。在「战争罪责」问题上，他暗示战争演变为持久消耗战很大程度上应归因于奥匈帝国。该书以编年体组织、侧重于战略与战役层面（一般不下沉到军以下级别），社会史维度（饥饿、疾病、劳工、性别问题）虽有涉及但非重点。加拿大历史杂志（1998年）发表Roy A. Prete的书评，推荐为必读文献。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Great Departure  Mass Migration from Eastern Europe and the Making of the Free World (Tara Zahra) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Great Departure: Mass Migration from Eastern Europe and the Making of the Free World", "author": "Tara Zahra", "year": 2016, "language": "英文", "publisher": "W.W. Norton", "description": "Tara Zahra（芝加哥大学东欧史教授、麦克阿瑟天才奖与古根海姆奖得主）的《大离去：东欧的大规模移民与自由世界的塑造》是一部具有范式转换意义的跨国移民史著作，2016年由W.W. Norton出版（392页）。1846至1940年间，超过5000万欧洲人迁往美洲——这是人类历史上规模最大的移民潮之一。Zahra的学术贡献在于将分析视角从传统的接收国中心（如美国的移民同化叙事）转向了此前被学术界系统忽视的「输出国视角」——特别是奥匈帝国及其继承国（捷克斯洛伐克、波兰等）如何体验、管理与回应这一大规模人口外流。全书核心论点挑战了「迁徙=自由」的常识等式：东欧各国政府因担忧丧失宝贵劳动力与兵源，远在冷战铁幕之前就积极寻求限制向外移民——20世纪的移民限制实际上是「西方仇外情绪与东欧保护主义之间勾结的产物」。Zahra还揭示了各国如何将移民作为政策工具——鼓励族群与宗教少数群体离开（如犹太人），同时限制「理想」民族群体的出境——这种以族群同质性为逻辑的「过滤」思维与两次大战之间的人口交换，为先后的种族净化与冷战欧洲的分割设定了先例。该书将这段历史与后1989年移民、欧盟扩大与难民危机等当代议题建立了强有力的联系，被广泛赞誉为对理解今日移民与难民辩论不可或缺的历史深度注脚。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。W.W. Norton 2016年出版。EPUB元数据需人工核对。", "priority_tier": "standard"},
    {"filename": "The Great Powers and the European States System 1814-1914 (2nd Edition) (F.R. Bridge, Roger Bullen) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Great Powers and the European States System, 1814-1914", "author": "F.R. Bridge and Roger Bullen", "year": 2005, "language": "英文", "publisher": "Pearson Longman", "description": "F.R. Bridge与Roger Bullen合著的《列强与欧洲国家体系，1814-1914》是19世纪欧洲国际关系史的标准教科书，2005年Pearson Longman出版的第二版（viii+365页，附地图）是对1980年初版的重大修订与扩充——篇幅几乎翻倍，融入了最新研究成果。本书以九章的清晰结构覆盖了从拿破仑战争结束至一战爆发的整整一个世纪的欧洲大国政治：从维也纳会议后欧洲秩序的重建与神圣同盟、1823-1830年间「各国自顾」的转向、1830-1856年从革命到克里米亚战争的国际危机管理、1856-1871年维也纳体系在意大利与德意志统一战争中的摧毁、1871-1879年新秩序的检验、1879-1895年保守大国主导体系、1895-1911年的不稳定均势、到1911-1914年的极化与战争爆发。全书以「欧洲国家体系」的概念为分析框架——追踪大国协调（Concert of Europe）的功能与失灵、均势政治的运行逻辑、以及同盟体系的形成与瓦解，特别突显了奥匈帝国作为「体系不可或缺的保守支柱」在国际秩序中的独特地位——一个其内部脆弱性持续驱动其外交政策走向的多民族大国角色。附有详尽参考书目（pp. 348-355）。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Habsburg Empire A New History (Pieter M. Judson) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Habsburg Empire: A New History", "author": "Pieter M. Judson", "year": 2016, "language": "英文", "publisher": "Belknap Press of Harvard University Press", "description": "Pieter M. Judson的《哈布斯堡帝国：一部新历史》是21世纪最具影响力的哈布斯堡通史修订主义著作，2016年由哈佛大学出版社Belknap分社出版（xiii+567页），荣获Choice杰出学术著作奖。Judson（欧洲大学学院19-20世纪史教授）系统地拒绝了将哈布斯堡帝国描绘为「功能失调的、时代错置的敌对族群的拼缀物」的传统叙事——这种叙事长期以来将帝国的崩溃归结为民族主义冲突的必然结果。他的核心修正是：共享的帝国制度、行政实践与文化项目为公民提供了跨越语言、宗教与区域分野的根本性共同经验——从义务教育到铁路网络、从征兵制到福利立法——这些制度性的帝国基础设施实际上持续加深了哈布斯堡统治的合法性而非侵蚀它。民族主义确实削弱了帝国的凝聚力，但并非其崩溃的唯一或首要原因——Judson将决定性因素指向战时条件与军事独裁体制对帝国制度合法性的摧毁性冲击。全书以八章覆盖从18世纪到1918年后的帝国史，其中「日常帝国，我们的帝国，1880-1914」一章尤为精彩——以社会史与日常生活史的微观视角展示了帝国晚期普通公民的多元帝国经验。Tim Blanning在《华尔街日报》赞誉其「清晰、优雅、充满令人惊讶与启发的细节」；Financial Times称其为「引人入胜的重新评价」。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。哈佛大学出版社2016年出版。EPUB元数据需人工核对。", "priority_tier": "high"},
    {"filename": "The Habsburg Empire, 1790-1918 (C.A. Macartney) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Habsburg Empire, 1790-1918", "author": "C.A. Macartney", "year": 1968, "language": "英文", "publisher": "Weidenfeld & Nicolson", "description": "C.A. Macartney的《哈布斯堡帝国，1790-1918》是20世纪英语学界哈布斯堡通史编纂的里程碑式巨著，1968年由伦敦Weidenfeld & Nicolson出版（xiv+886页，附6幅地图）。Macartney（1895-1978）系牛津大学万灵学院研究员、英国学术院院士、爱丁堡大学国际关系教授，毕生致力于中欧特别是匈牙利与哈布斯堡帝国史的研究。本书从利奥波德二世继位写至1918年帝国解体，以惊人的细节密度（近900页正文）覆盖了哈布斯堡君主国从开明专制晚期经拿破仑战争、三月革命前时期（Vormärz）、1848年革命、新专制主义（Neoabsolutism）、1867年奥匈妥协、自由主义时代、民族冲突的激化、到一战与解体的完整历程。Macartney以其深厚的多语种史料功底（匈牙利语、德语、捷克语、意大利语等）和对匈牙利政治史的特别关注著称——书中的匈牙利视角比同期的任何英文通史都更加详尽与同情。尽管其亲匈牙利立场与以民族政治为叙事轴心的传统框架在Judson（2016年）等新一代修订主义史家的批评下已显时代局限，但在学术史上，Macartney的这部通史与其匈牙利专题著作（《匈牙利及其继承国》《十月十五日》）共同构成了20世纪中后期英语学界哈布斯堡研究的核心学术遗产。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。Weidenfeld & Nicolson 1968年出版。EPUB元数据需人工核对。1969年重印版使用的是不同的ISBN。", "priority_tier": "high"},
    {"filename": "The Habsburg Monarchy as a Customs Union Economic Development in Austria-Hungary in the Nineteenth Century (John Komlos) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Habsburg Monarchy as a Customs Union: Economic Development in Austria-Hungary in the Nineteenth Century", "author": "John Komlos", "year": 1983, "language": "英文", "publisher": "Princeton University Press", "description": "John Komlos的《作为关税同盟的哈布斯堡君主国：19世纪奥匈帝国的经济发展》是哈布斯堡经济史领域最具影响力的新古典经济学派（cliometrics）著作之一，1983年由普林斯顿大学出版社出版（xix+347页）。该书修订自Komlos在芝加哥大学的经济史博士论文（1978年），以计量经济学方法系统评估了19世纪中叶两项关键制度变革——奥地利与匈牙利之间关税同盟的形成（1850年）与农奴制的废除（1848年）——对帝国两半部经济发展的长期影响。Komlos利用大量定量数据（农业产出、工业产值、价格序列与贸易流量）论证：关税同盟通过消除内部贸易壁垒显著促进了帝国各地区之间的市场整合与经济专业化——匈牙利成为帝国的「粮仓」，而奥地利（特别是波希米亚与下奥地利）则发展为工业中心——但这种区域分工模式也固化了帝国内部的发展不均衡。在方法论上，Komlos的工作标志着哈布斯堡经济史从传统的制度描述史学向以新古典经济理论为指导、以统计验证为基础的定量研究范式转型的关键节点——其GDP估计值与后续学者（特别是Max-Stephan Schulze与David Good）的修正与争论构成了该领域此后数十年的核心学术对话。Nachum T. Gross在《美国历史评论》（1984年）发表书评。该书后多次重印平装本（Princeton Legacy Library），并发行电子书版。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"}
]

with open('baseline_extract.json', 'r', encoding='utf-8') as f:
    baseline = json.load(f)
baseline_by_fn = {b['filename']: b for b in baseline}

for entry in entries:
    fn = entry['filename']
    if fn in baseline_by_fn:
        b = baseline_by_fn[fn]
        entry['filepath'] = b['filepath']; entry['page_count'] = b.get('page_count', 0)
        entry['is_scanned'] = b.get('is_scanned'); entry['has_bookmarks'] = b.get('has_bookmarks')
        bm = b.get('bookmark_titles')
        entry['bookmark_titles'] = [item['title'] for item in bm if isinstance(item, dict)] if bm and isinstance(bm, list) else []

with open('bookdata.json', 'r', encoding='utf-8') as f: existing = json.load(f)
existing_fns = {b['filename'] for b in existing}; added = 0
for entry in entries:
    if entry['filename'] not in existing_fns: existing.append(entry); existing_fns.add(entry['filename']); added += 1
with open('bookdata.json', 'w', encoding='utf-8') as f: json.dump(existing, f, ensure_ascii=False, indent=2)

for entry in entries:
    ts = datetime.now().isoformat(); review = 'REVIEW' if entry.get('needs_review') else 'OK'
    with open('log.txt', 'a', encoding='utf-8') as lf:
        lf.write(f"{entry['filename']} | DONE | {ts} | conf={entry['extraction_confidence']} review={review} desc_src={entry['description_source']}\n")

print(f'Added {added}, total: {len(existing)}/142')
for e in entries: print(f"  [{e['extraction_confidence']}] {e['title'][:70]} | {e['author'][:50]} | {e['year']}")
