"""Generate and write remaining entries for books 112-142."""
import json, os
from datetime import datetime

entries = [
    # 112 - Hitchins
    {"filename": "The Rumanian national movement in Transylvania, 1780-1849 (Hitchins, Keith) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Rumanian National Movement in Transylvania, 1780-1849", "author": "Keith Hitchins", "year": 1969, "language": "英文", "publisher": "Harvard University Press", "description": "Keith Hitchins的《特兰西瓦尼亚的罗马尼亚民族运动，1780-1849》是哈佛历史专著丛书（Harvard Historical Monographs）第61卷，1969年由哈佛大学出版社出版（xi+316页），基于作者1964年在哈佛大学完成的博士论文。Hitchins聚焦于哈布斯堡帝国特兰西瓦尼亚大公国——帝国境内罗马尼亚人口最为集中的区域——追踪了从约瑟夫二世改革时期到1848年革命之间罗马尼亚民族运动的形成过程。全书的核心分析框架围绕希腊天主教会（东仪天主教会/Uniate Church）在罗马尼亚民族觉醒中的催化角色展开：1698-1701年部分特兰西瓦尼亚东正教神职人员与罗马的教会合一创造了罗马尼亚知识分子精英的第一个制度化平台——Blaj（巴拉斯法尔瓦）的希腊天主教主教区及其附属学校成为罗马尼亚民族思想的生产与传播中心。Hitchins逐一分析了「特兰西瓦尼亚学派」（Şcoala Ardeleană）的代表性人物——Samuil Micu、Gheorghe Şincai与Petru Maior——如何通过历史书写、语言学与政治请愿（特别是1791年Supplex Libellus Valachorum，向利奥波德二世提交的罗马尼亚民族政治权利请愿书）建构罗马尼亚民族的达契亚-罗马起源论与历史连续性理论。1848年革命中罗马尼亚人在Blaj召集的民族大会（参与人数多达4万）及其对哈布斯堡王朝的忠诚宣示——同时与匈牙利革命政府决裂——是该书叙事的高潮。详尽的书目论文（pp. 283-298）是该领域的核心文献指南。ACLS人文学科电子书项目后推出电子版。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 113 - Rogel
    {"filename": "The Slovenes and Yugoslavism, 1890-1914 (Rogel, Carole) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Slovenes and Yugoslavism, 1890-1914", "author": "Carole Rogel", "year": 1977, "language": "英文", "publisher": "East European Monographs (distributed by Columbia University Press)", "description": "Carole Rogel的《斯洛文尼亚人与南斯拉夫主义，1890-1914》是英语学界关于晚期哈布斯堡帝国内斯洛文尼亚民族政治的最详尽研究之一，1977年由East European Monographs出版（No. 24，vii+167页）。全书系统分析了斯洛文尼亚政治光谱上三大派别——斯洛文尼亚人民党（Slovene People's Party，追求在帝国框架内以「三元主义」[Trialism]解决南部斯拉夫问题）、民族进步党（National Progressive Party，自由派斯洛文尼亚民族主义）、以及南斯拉夫社会民主党（Yugoslav Social Democratic Party，社会主义者的民族政策）——如何在1890年至一战爆发之间围绕「南斯拉夫主义」（Yugoslavism）这一核心理念展开意识形态竞争与政治博弈。Rogel依次考察了1908-1909年波斯尼亚兼并危机如何激化了对奥匈帝国框架内解决方案的忠诚度考验、文化南斯拉夫主义中「Vraz-Prešeren辩论」的复兴——即斯洛文尼亚文学与语言是否应融入更广泛的塞尔维亚-克罗地亚文化共同体的持久争论、以及1912-1913年巴尔干战争如何促使学生与独立知识分子群体转向追求奥地利框架之外的南部斯拉夫统一方案。该书的学术价值在于揭示了「南斯拉夫主义」并非一个单一的、既定的意识形态目标——而是在不同政治阵营、不同时间节点上具有根本不同制度含义（从三元主义到联邦主义到完全独立）的多元竞争性概念丛。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    # 114 - landownership paper
    {"filename": "The changing pattern of landownership in Hungary, 1867-1914.pdf", "title": "The Changing Pattern of Landownership in Hungary, 1867-1914", "author": "Unknown", "year": 1974, "language": "英文", "publisher": None, "description": "本论文考察1867年奥匈妥协至第一次世界大战爆发之间匈牙利土地所有权模式的变迁，聚焦这一时期匈牙利农业社会结构的转型。核心议题可能包括：1848年农奴制废除后土地市场的发展与大地产（latifundia）与小农持有之间的张力、信贷制度与土地抵押对农民土地持有稳定性的影响、以及农业人口过剩与向外移民之间的关系。在奥匈二元体制下，匈牙利王国保留了对其内部经济政策的广泛自主权，这深刻塑造了其土地所有权结构与农业发展路径。该论文可能发表于Economic History Review或Agricultural History等经济史期刊（19页，非扫描版PDF）。作者与确切出版信息需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "19页非扫描PDF，未提供作者或期刊信息。无法从首页提取文字。推测为1970年代经济史论文。建议人工核对PDF首页确认作者、期刊来源与出版年份。", "priority_tier": "standard"},
    # 115 - civic vs ethnic nationalism paper
    {"filename": "The history of the dichotomy of civic Western and ethnic Eastern nationalism.pdf", "title": "The History of the Dichotomy of Civic Western and Ethnic Eastern Nationalism", "author": "Unknown", "year": 2000, "language": "英文", "publisher": None, "description": "本论文追溯民族主义研究中最具影响力的概念二分法之一——「公民的/西方的」与「族群的/东方的」民族主义（civic Western vs. ethnic Eastern nationalism）——的学术史脉络。这一区分最经典的理论表述源自Hans Kohn的《民族主义理念》（The Idea of Nationalism, 1944），此后在Ernest Gellner、Anthony D. Smith、Liah Greenfeld与Rogers Brubaker等学者的著作中被不断修正、批评与重构。该论文可能从思想史路径系统梳理这一二分法的学术谱系，并特别聚焦于其对东欧与哈布斯堡民族主义研究的影响——包括Pieter Judson等学者所倡导的「民族无差异」（national indifference）概念对Kohn式二分法的根本性挑战。也可能涉及John Plamenatz、Miroslav Hroch等中欧学者对这一概念框架的早期参与与修正。25页非扫描版PDF，作者与确切出版信息需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "25页PDF，首页未提供明确作者或出版信息。学术定位基于model knowledge推测。建议人工核对PDF首页确认作者、期刊与出版年份。", "priority_tier": "standard"},
    # 116 - Evans
    {"filename": "The making of the Habsburg monarchy, 1550-1700  an interpretation (Evans, Robert John Weston) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Making of the Habsburg Monarchy, 1550-1700: An Interpretation", "author": "R.J.W. Evans", "year": 1979, "language": "英文", "publisher": "Clarendon Press / Oxford University Press", "description": "R.J.W. Evans（牛津大学现代史Regius教授）的《哈布斯堡君主国的缔造，1550-1700：一种解释》是早期现代哈布斯堡史领域最具影响力的著作之一，1979年由牛津Clarendon出版社出版（xxiii+531页），1980年荣获沃尔夫森文学奖（历史类）。Evans从根本上重构了哈布斯堡君主国在16-17世纪崛起的历史解释——他不走传统的军事-外交叙事路径，转而论证使哈布斯堡多元领地逐步凝聚为一体的是一种「共同而独特的文化」：反宗教改革（Counter-Reformation）推动的社会与文化变革、区域与中央政府的互动模式、以及从文艺复兴人文主义到巴洛克的思想转型——这三个维度共同塑造了一种「共识先于强制」的整合模式。Evans大胆提出哈布斯堡家族本质上是「危机的受益者」——「他们的成功源于其虚弱而非其强大」——君主国不是现代意义上的「国家」，而是一种「温和向心的、由令人困惑的异质元素构成的凝聚体」。该书以其对捷克语与匈牙利语地方史料的广泛掌握——此前多数西方学者无法接触——而著称，Tim Blanning誉之为「近几十年来关于早期现代欧洲史出版的最重要著作之一」。全书分三大部分：政治-社会-经济发展、离心力量（奥地利、波希米亚、匈牙利与德意志帝国各章）、以及涵盖学术史与巴洛克知性世界的思想-文化史。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 117 - Whiteside
    {"filename": "The socialism of fools  Georg Ritter von Schönerer and Austrian Pan-Germanism (Whiteside, Andrew Gladding, 1921-) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Socialism of Fools: Georg Ritter von Schönerer and Austrian Pan-Germanism", "author": "Andrew G. Whiteside", "year": 1975, "language": "英文", "publisher": "University of California Press", "description": "Andrew G. Whiteside的《愚人的社会主义：格奥尔格·里特·冯·舍内雷尔与奥地利泛日耳曼主义》是关于阿道夫·希特勒在维也纳时期最重要的思想前驱——格奥尔格·冯·舍内雷尔（Georg Ritter von Schönerer, 1842-1921）——的最权威英文传记研究，1975年由加州大学出版社出版（x+404页）。书名引用了费迪南德·克罗纳维特（Ferdinand Kronawetter）关于反犹主义的名言——「愚人的社会主义」（der Sozialismus des dummen Kerls）。Whiteside将舍内雷尔置于晚期哈布斯堡奥地利激进德意志民族主义的完整思想与政治语境中，系统分析了舍内雷尔的激进德意志民族主义在1870-1890年代通过群众政治动员——以反犹主义、反天主教「脱离罗马！」运动（Los von Rom!）与暴力议会阻挠主义为三大支柱——对奥地利政治版图的重塑冲击。Whiteside的核心理学判断是：舍内雷尔的历史重要性不在于其个人政治生涯的惨淡失败（因性格缺陷与策略失误而屡屡自毁），而在于他以极端形式清晰表达了当时已在奥地利德意志中产阶级中广泛存在的思想倾向——从而照亮了希特勒从中涌现的精神背景。该书考察了舍内雷尔的早期民粹魅力、1888年因率众袭击《新维也纳日报》（Neues Wiener Tagblatt）编辑部而被判入狱并暂时政治失格的事件、1890年代泛日耳曼党内的权力斗争、以及1907年后的衰落。William A. Jenks在《美国历史评论》（1977年）发表书评。本书是Whiteside此前1962年著作《1918年前的奥地利国家社会主义》——一部关于波希米亚德意志激进民族主义工人运动的研究——的延续与深化。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 118 - Tisza István
    {"filename": "Tisza István (Vermes, Gabor) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "István Tisza: The Liberal Vision and Conservative Statecraft of a Magyar Nationalist", "author": "Gabor Vermes", "year": 1985, "language": "英文", "publisher": "East European Monographs (distributed by Columbia University Press)", "description": "Gabor Vermes（罗格斯大学历史学教授，匈牙利裔美国学者）的《蒂萨·伊什特万：一位马扎尔民族主义者的自由主义愿景与保守治国术》是关于奥匈帝国晚期最具权势与争议性的匈牙利政治家的首部重要英文传记，1985年由East European Monographs出版（No. 184，xii+627页，附16页照片）。蒂萨·伊什特万（1861-1918）两度出任匈牙利首相（1903-1905年，1913-1917年），是1913-1917年间决定帝国命运的核心政治人物。Vermes的副标题精准概括了其核心论点——蒂萨既是一位真诚的自由主义者（在理论上深信法治与议会主权、政教分离、文化权利与自由放任经济学），又是一位保守的国家治理者（在实践上致力于维护现存政治与社会秩序）——这一看似矛盾的双重人格根源于「基本匈牙利困境」：一个在其自身边界内仅拥有相对族群多数的国家，被更大强国与领土收复主义邻国所包围的脆弱处境。全书基于对匈牙利与外国档案——维也纳、柏林、伦敦、华盛顿与斯坦福大学胡佛研究所——的多年详尽研究，深刻修正了蒂萨在国内外的负面历史形象。最具原创性的章节《思想的碰撞》探讨了蒂萨的「旧自由主义」与时代激进的青年进步派之间的冲突——论证两个阵营之间的共通之处比任何一方（以及后世）所承认的都更多。1985年（Ferenc Pölöskei匈牙利文蒂萨传出版同年）成为蒂萨学术研究的分水岭年份。附有详尽参考书目（pp. 568-605）。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    # 119 - Healy
    {"filename": "Vienna and the Fall of the Habsburg Empire Total War and Everyday Life in World War I (Maureen Healy) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Vienna and the Fall of the Habsburg Empire: Total War and Everyday Life in World War I", "author": "Maureen Healy", "year": 2004, "language": "英文", "publisher": "Cambridge University Press", "description": "Maureen Healy（俄勒冈州立大学历史系助理教授）的《维也纳与哈布斯堡帝国的覆灭：第一次世界大战中的总体战与日常生活》是新一代哈布斯堡一战社会文化史的代表作，2004年由剑桥大学出版社出版于「现代战争的社会与文化史」丛书（xv+333页），2000年荣获弗兰克尔奖（Fraenkel Prize）。Healy的核心论点是：维也纳作为城市在哈布斯堡国家于1918年秋季从军事与外交意义上崩溃之前就已先行瓦解——而且这一「社会分解」的主要驱动力并非民族冲突（这是传统哈布斯堡崩溃叙事的焦点），而是两种基本物资的短缺：食品与可信信息。全书分为两大部分。第一部分「政治与表征」依次分析：食品与牺牲政治——饥饿直接导致了维也纳7-11%的死亡（在20-30%中为促成因素），城市与乡村、前线与后方、奥地利与匈牙利之间的相互指责如何毒化了社会团结；娱乐、宣传与1916-1917年维也纳战争展览（两月内吸引逾50万参观者）；以及审查制度、谣言与告密——信息的缺失如何导致社会原子化与「真相危机」。第二部分「国家与家庭」考察了女性、儿童与留在家中的男性在总体战中的经验——女性未能展现预期的团结反而相互背叛与暴力、营养不良的儿童无法达到英雄主义宣传的理想、「无父社会」中留守男性被污名为「逃避服役的犹太人」与「阴谋的捷克人」。Nancy Wingfield在Habsburg（2005年）赞誉其为「力作」，是「关于哈布斯堡君主国毁灭的最佳新近研究之一」。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    # 120 - Beller Vienna and Jews
    {"filename": "Vienna and the Jews, 1867-1938  a cultural history (Beller, Steven, 1958-) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Vienna and the Jews, 1867-1938: A Cultural History", "author": "Steven Beller", "year": 1989, "language": "英文", "publisher": "Cambridge University Press", "description": "Steven Beller的《维也纳与犹太人，1867-1938：一部文化史》是维也纳世纪末现代文化研究中具有里程碑意义的著作，1989年由剑桥大学出版社出版（x+271页，附18幅表格）。Beller通过统计分析提出了一个无法回避的核心事实——犹太人在维也纳现代高雅文化的几乎所有领域中都占据着不成比例的突出地位——进而追问：这种「犹太性」（Jewishness）的文化意义是什么？其核心论点是：维也纳世纪之交的文化「爆炸」并非仅仅是犹太裔个体碰巧在其中扮演了突出角色的普遍文化现象——相反，其内容、形式与问题意识深刻地、因果性地植根于其缔造者的特定犹太背景、以及他们对自身「作为犹太人」处境的不同个体应对方式。全书以1867年奥匈妥协（给予犹太人完全法律平等）至1938年德奥合并为时间框架，覆盖了勋伯格（Schönberg）、卡尔·克劳斯（Karl Kraus）、维特根斯坦等核心人物及其所处的维也纳思想与文化网络。伦敦书评（London Review of Books）赞誉其为「一个大胆、激动人心且大体上令人信服的尝试——从起源来解释内容」、「一项重大贡献」。泰晤士高等教育增刊称其为「清晰的知识研究」、论点「令人兴奋」。加拿大的历史杂志称赞其「扎实的研究、论证清晰与复杂、文笔优雅」。Beller（1958年生）系独立学者，后出版《弗朗茨·约瑟夫传》（亦收入本馆藏）等多部哈布斯堡与犹太史著作。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 121 - WP106 Schulze
    {"filename": "WP106schulzeRegional income dispersion and market potential in the late nineteenth century Hapsburg Empire.pdf", "title": "Regional Income Dispersion and Market Potential in the Late Nineteenth Century Hapsburg Empire", "author": "Max-Stephan Schulze", "year": 2007, "language": "英文", "publisher": "LSE Economic History Working Papers", "description": "Max-Stephan Schulze的这篇工作论文（LSE经济史工作论文系列，编号WP106）利用新经济地理学（New Economic Geography）的分析框架考察19世纪晚期哈布斯堡帝国的区域收入差异与市场潜力之间的关系。基于Schulze此前关于1870-1913年奥地利GDP估计的方法论基础，本文利用区域层面的收入数据——可能涵盖奥地利与匈牙利各王冠领地的工业化差异、城市化梯度以及到主要市场中心的距离——来检验市场潜力（market potential）对区域人均收入水平的影响。该研究对于理解哈布斯堡帝国境内工业化过程中空间不平衡的机制——为什么波希米亚、下奥地利与大布达佩斯地区发展迅速而加利西亚、布科维纳与达尔马提亚等边缘省份持续落后——提供了定量分析基础。Schulze的工作论文系列（包括本论文以及No. 36/97、No. 92/05与No. 100/07，均收入本馆藏）共同构成了英语学界对哈布斯堡帝国经济史最系统的定量研究方法论体系。36页PDF。", "description_source": "model_knowledge", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "文件名为WP106schulze，无明确标题。通过文件名推断为Schulze关于区域收入差异与市场潜力的LSE工作论文。确切标题、编号与出版年份需人工核对PDF首页确认。", "priority_tier": "standard"},
    # 122 - Wittgenstein's Vienna
    {"filename": "Wittgenstein's Vienna (Allan Janik, Stephen Toulmin) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Wittgenstein's Vienna", "author": "Allan Janik and Stephen Toulmin", "year": 1973, "language": "英文", "publisher": "Simon and Schuster / Weidenfeld and Nicolson", "description": "Allan Janik与Stephen Toulmin（1922-2009）合著的《维特根斯坦的维也纳》是维也纳世纪末思想史领域最具原创性与影响力的跨学科著作之一，1973年由Simon & Schuster（纽约）与Weidenfeld & Nicolson（伦敦）出版（314页，附插图）。该书同时处理四重对象：一本书及其意义（维特根斯坦的《逻辑哲学论》/Tractatus）、一个人及其思想（路德维希·维特根斯坦）、一种文化及其核心关切（世纪之交的维也纳）、以及一个社会及其问题（最后几十年的哈布斯堡帝国）。Janik与Toulmin的根本论点是：维特根斯坦的早期哲学——《逻辑哲学论》——不能在剑桥分析哲学的内部谱系中被孤立理解，而必须被重置于维也纳世纪末的特定文化与政治语境中：卡尔·克劳斯的语言伦理批判、阿道夫·洛斯的装饰批判与功能主义、勋伯格的十二音体系、以及维也纳圈子中对「语言批判」（Sprachkritik）的普遍关切——所有这些思想运动共享着一种将伦理、美学与逻辑从根本上绑定在一起的文化敏感性，而正是这种敏感性构成了《逻辑哲学论》中那著名第七命题「对于不可言说的东西，必须保持沉默」背后的知性世界。全书九章覆盖了哈布斯堡维也纳作为「悖论之城」的社会-政治分析、克劳斯对语言腐化与道德衰败的双重批判、以及维特根斯坦哲学的人类学-文化解读——被认为是将分析哲学传统与欧陆文化思想史传统进行创造性对话的最成功的尝试之一。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    # 123 - duplicate Schulze paper
    {"filename": "__libfile_REPOSITORY_Content_Schulze, M_Patterns of growth and stagnation in the late nineteenth century Habsburg economy_Patterns of growth and stagnation in the late nineteenth century Habsburg economy (LSE RO).pdf", "title": "Patterns of Growth and Stagnation in the Late Nineteenth Century Habsburg Economy [duplicate copy]", "author": "Max-Stephan Schulze", "year": 2000, "language": "英文", "publisher": "European Review of Economic History, Vol. 4, No. 3", "description": "本文件为Max-Stephan Schulze《19世纪晚期哈布斯堡经济的增长与停滞模式》（2000年）的LSE Research Online仓库下载副本，是同一篇论文的第二个副本（另一版本已录入本馆藏[67]号记录）。该文发表于European Review of Economic History第4卷第3期（pp. 311-340），构建了1870-1913年间奥地利与匈牙利各自GDP的新年度估计值，论证奥地利（内莱塔尼亚）人均收入增长未能以与其相对收入地位相称的速度推进，而匈牙利则记录了明显更高的人均收入增长率——Schulze以1873年维也纳股市崩盘后奥地利资本流入匈牙利来解释这一帝国两半部经济增长轨迹的分化。两个文件内容完全相同——文件名中的『__libfile_REPOSITORY_Content_』前缀表明本文件直接下载自LSE Research Online的机构学术仓库。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "为[67]号书目记录的重复副本。两文件为同一篇论文的不同数字副本：一为z-library版本，一为LSE Research Online机构仓库版本。内容相同。", "priority_tier": "standard"},
    # 124 - Macedonian documents
    {"filename": "austro-hungarian documents relating ti the macedonian struggle 1896-1912 (F.R. BRIDGE) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Austro-Hungarian Documents Relating to the Macedonian Struggle, 1896-1912", "author": "F.R. Bridge (editor)", "year": 1976, "language": "混合", "publisher": "Institute for Balkan Studies (Thessaloniki)", "description": "F.R. Bridge编选的《奥匈帝国关于马其顿斗争的文献，1896-1912》是研究晚期奥斯曼帝国巴尔干问题与列强外交的重要一手史料汇编，1976年由塞萨洛尼基巴尔干研究所出版于其丛书（No. 149，527页）。该卷汇集了1896-1912年间奥匈帝国外交档案中涉及马其顿斗争——即希腊、保加利亚、塞尔维亚与罗马尼亚等巴尔干民族国家及其在奥斯曼马其顿省份内部的革命组织（特别是Internal Macedonian Revolutionary Organization/IMRO与Supreme Macedonian-Adrianople Committee/SMAC）之间围绕领土、人口与教会管辖权展开的多层次暴力竞争——的核心外交文件。序言与说明为英文，文献正文为德文原文（奥匈帝国外交工作语言）。这些文献对于理解：1）奥匈帝国巴尔干政策的决策过程与内部张力（维也纳与布达佩斯之间的分歧）；2）列强在马其顿改革问题上的外交协调与竞争（特别是Mürzsteg改革方案[1903年]的设计与失败）；3）1912-1913年巴尔干战争的外交前奏——具有不可替代的一手史料价值。Bridge另著有《从萨多瓦到萨拉热窝》（亦收入本馆藏），是奥匈外交史领域的权威学者。附有文献列表（pp. 487-505）与索引。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 125 - Sarajevo Remak
    {"filename": "saravejo the story of a political murder (joachim remak) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Sarajevo: The Story of a Political Murder", "author": "Joachim Remak", "year": 1959, "language": "英文", "publisher": "Criterion Books", "description": "Joachim Remak（俄勒冈州刘易斯与克拉克学院历史学讲师）的《萨拉热窝：一起政治谋杀的故事》是关于1914年6月28日弗朗茨·斐迪南大公遇刺事件的最著名英文叙事史之一，1959年由Criterion Books出版（xv+301页，附照片与来源说明）。Remak以生动的新闻叙事风格讲述了七名年轻密谋者——以加夫里洛·普林西普（Gavrilo Princip）为首——如何计划并执行了这起引爆第一次世界大战的刺杀事件。该书最引人注目——也是最具争议——的论点是：弗朗茨·斐迪南之所以被刺杀，并非因为他是南部斯拉夫人的敌人，正相反——恰恰因为他倡导的「三元主义」（Trialism，将南部斯拉夫人提升为帝国内与德意志人与马扎尔人平等的第三构成民族）改革方案威胁要从根本上解决南部斯拉夫问题，从而瓦解塞尔维亚民族统一主义（irredentism）的合法性基础。这一论点在著名历史学家A.J.P. Taylor（于《纽约时报》1959年6月28日发表长文评述）看来「几乎没有值得支持的理由」——Taylor的总评是Remak「将民族自由的拥护者视为愚蠢或邪恶的」，但承认其文笔为「优美的、可读的、生动的叙事，以趣味与激情引领读者前进」。该书还提出了关于塞尔维亚「黑手社」首领阿皮斯（Dragutin Dimitrijević/Apis）亲自策划与安排刺杀的指控——Taylor批评此说证据「非常非常少」。尽管其核心论点充满争议，该书至今仍是萨拉热窝事件研究领域不可绕过的经典叙事。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    # 126 - Jaszi
    {"filename": "the dissolution of the habsburg monarchy (oscar jaszi) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Dissolution of the Habsburg Monarchy", "author": "Oscar Jászi", "year": 1929, "language": "英文", "publisher": "University of Chicago Press", "description": "Oscar Jászi（Oszkár Jászi, 1875-1957）的《哈布斯堡君主国的解体》是关于帝国崩溃的最重要亲历者-学者分析之一，1929年由芝加哥大学出版社出版于「公民塑造研究」丛书（xxiv+488页）。Jászi是20世纪匈牙利政治思想史上最引人入胜的人物之一——激进民主主义知识分子、1900年《二十世纪》（Huszadik Század）杂志创始人、1914年匈牙利激进党领袖、1918年10月革命后任卡洛伊（Mihály Károlyi）政府中的民族事务部长——在1919年苏维埃共和国建立后流亡海外，最终在美国俄亥俄州奥伯林学院任政治学教授终老。这部著作从流亡的民主派联邦主义者视角提供了对帝国解体原因的最系统理论分析。Jászi的核心概念框架是「民族重力」（gravamina nationum）——他认为哈布斯堡帝国并非因民族冲突本身而死（各民族之间的经济与功能相互依赖是真实的且持续加深的），而是因为帝国未能发展出一种能够将这些多元民族忠诚转化为对共同国家框架之认同的『民主化』制度安排——帝国的政治精英们——哈布斯堡王朝本身、军队高层、天主教教会等级制、以及马扎尔与德意志贵族寡头——系统性地抵制了任何可能威胁其自身特权地位的真正的联邦制与民主化改革，从而在民族主义时代注定走向解体。该书可以被视为对哈布斯堡帝国「民主化悖论」的最早的、也是最具亲历者深度的系统性理论分析。前言中指出该书「在某种意义上是作者此前著作《民族国家的演化与民族问题》（布达佩斯，1912年，匈牙利文）的延续」。附有详尽参考书目（pp. 461-480）。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    # 127-130 - Österreich-Ungarns letzter Krieg (4 volumes)
    {"filename": "Österreich-Ungarns letzter Krieg 1914-1918 (Glaise von Horstenau, Edmund, 1882- etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "Österreich-Ungarns letzter Krieg 1914-1918, Band I: Das Kriegsjahr 1914", "author": "Österreichisches Bundesministerium für Heereswesen und Kriegsarchiv; unter der Leitung von Edmund Glaise-Horstenau", "year": 1930, "language": "德文", "publisher": "Verlag der Militärwissenschaftlichen Mitteilungen (Wien)", "description": "《奥地利-匈牙利最后的战争，1914-1918》是奥地利第一共和国联邦陆军部与战争档案馆编纂的奥匈帝国一战官方战史，是研究哈布斯堡帝国军事史最重要的一手资料与权威参考著作。全书共七卷正文加索引卷与补编，1930-1938年间由维也纳军事科学出版社陆续出版。编纂工作由Edmund Glaise-Horstenau（后成为纳粹时期奥地利副总理）主持，Josef Brauner、Rudolf Kiszling等奥地利军事档案学家参与编辑。该系列以逐战场、逐战役的详尽程度记录了奥匈军队在各条战线上的军事行动——从塞尔维亚战役（1914年）、东线对俄作战（1914-1917年加利西亚、喀尔巴阡山、戈尔利采-塔尔努夫突破等）、意大利战线（1915-1918年伊松佐河、特伦蒂诺、皮亚韦河）、到罗马尼亚战役（1916-1917年）——并附有大量作战地图、兵力部署表与伤亡统计。其详细程度至今在英文学界无可替代——特别是对东线与意大利战线的覆盖（俄罗斯从未完成其正式一战史，意大利、罗马尼亚与塞尔维亚的官方战史也无英译本）。然而作为官方战史，该系列继承了美化军队、淡化政治责任、并系统边缘化非德意志民族的军事贡献等明显的制度性偏见。Hew Strachan等当代权威一战史家仍视其为不可或缺的参考工具。本馆藏为第一卷：战争年份1914年（840页，扫描版，不含书签）。Stan Hanna的英译本（Legacy Books Press, 2023年，第三卷英译已收入本馆藏）正在逐步填补英语学界对这一巨著的系统接触空白。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "无书签，确切卷次需人工核对封面/标题页确认。推测为第一卷（1914年战事），840页。该系列共七卷加索引与补编各一卷，1930-1938年出版。", "priority_tier": "high"},
    {"filename": "Österreich-Ungarns letzter Krieg 1914-1918 (Glaise von Horstenau, Edmund, 1882- etc.) (z-library.sk, 1lib.sk, z-lib.sk) (1).pdf", "title": "Österreich-Ungarns letzter Krieg 1914-1918, Band II: Das Kriegsjahr 1915, Erster Teil", "author": "Österreichisches Bundesministerium für Heereswesen und Kriegsarchiv; unter der Leitung von Edmund Glaise-Horstenau", "year": 1931, "language": "德文", "publisher": "Verlag der Militärwissenschaftlichen Mitteilungen (Wien)", "description": "《奥地利-匈牙利最后的战争，1914-1918》德文原版官方战史第二卷，覆盖1915年战事的前半部分。该卷聚焦于东线的冬季-春季战役——喀尔巴阡山冬季战役（1915年1-3月）中奥匈军队在极端严寒条件下遭受的巨大伤亡（约80万人损失，其中大部分为冻伤与疾病）、戈尔利采-塔尔努夫（Gorlice-Tarnów）突破（1915年5月）——德军主导的大规模攻势逆转了东线态势、收复普热梅希尔（Przemyśl）要塞与伦贝格（Lemberg/Lwów/Lviv）——以及与此同时意大利于1915年5月23日对奥匈宣战后伊松佐战线最初的几次战役。这是奥匈帝国在战争中军事命运最戏剧性的转折年：从年初在东线喀尔巴阡山面临军事崩溃的绝望边缘，到仲夏借助德国增援取得巨大收复领土的胜利，再到被意大利「背后捅刀」而不得不在两条战线上作战。774页扫描版PDF，不含书签。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "确切卷次与内容需人工核对。推测为第二卷（1915年前半），774页。", "priority_tier": "high"},
    {"filename": "Österreich-Ungarns letzter Krieg 1914-1918 (Glaise von Horstenau, Edmund, 1882- etc.) (z-library.sk, 1lib.sk, z-lib.sk) (2).pdf", "title": "Österreich-Ungarns letzter Krieg 1914-1918, Band III: Das Kriegsjahr 1915, Zweiter Teil", "author": "Österreichisches Bundesministerium für Heereswesen und Kriegsarchiv; unter der Leitung von Edmund Glaise-Horstenau", "year": 1932, "language": "德文", "publisher": "Verlag der Militärwissenschaftlichen Mitteilungen (Wien)", "description": "《奥地利-匈牙利最后的战争，1914-1918》德文原版官方战史第三卷，覆盖1915年战事的后半部分。该卷聚焦于奥匈帝国秋季对塞尔维亚的最终征服（1915年10-12月）——在德国元帅马肯森（August von Mackensen）统一指挥下，德军与奥匈军队从北面、保加利亚军队从东面同时入侵塞尔维亚——塞尔维亚军队在极端困苦的冬季撤退中穿越阿尔巴尼亚山区至科孚岛（所谓「塞尔维亚各各他」/Serbian Golgotha，约20万士兵与平民死于行军途中）、以及意大利战线上持续的消耗战。这也是奥匈帝国外交与军事决策中深刻内部张力日益加剧的时期——康拉德（Conrad von Hötzendorf）与德国总参谋部法尔肯海因（Falkenhayn）之间不断恶化的争端、贝希托尔德（Berchtold）被布里昂（Burián）取代为外相（1915年1月）、以及匈牙利首相蒂萨对帝国战争目标的持续质疑。648页扫描版PDF，不含书签。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "确切卷次需人工核对确认。推测为第三卷（1915年后半），648页。", "priority_tier": "high"},
    {"filename": "Österreich-Ungarns letzter Krieg 1914-1918 (Glaise von Horstenau, Edmund, 1882- etc.) (z-library.sk, 1lib.sk, z-lib.sk) (3).pdf", "title": "Österreich-Ungarns letzter Krieg 1914-1918, Band IV: Das Kriegsjahr 1916, Erster Teil", "author": "Österreichisches Bundesministerium für Heereswesen und Kriegsarchiv; unter der Leitung von Edmund Glaise-Horstenau", "year": 1933, "language": "德文", "publisher": "Verlag der Militärwissenschaftlichen Mitteilungen (Wien)", "description": "《奥地利-匈牙利最后的战争，1914-1918》德文原版官方战史第四卷，覆盖1916年战事的前半部分。该卷聚焦于1916年春季至夏季间两条主要战线的作战——意大利战线：康拉德期待已久的南蒂罗尔攻势（Strafexpedition/「惩罚性远征」，1916年5-6月），虽取得了初期战术成功但最终因布鲁西洛夫（Brusilov）攻势在东线的爆发而被迫中止；东线：俄军西南方面军在布鲁西洛夫将军指挥下发起了大战中俄军最具毁灭性的进攻（1916年6-9月）——数百公里战线上的大规模突破使奥匈军队遭受约75万人的惊人损失（其中38万被俘），从根本上粉碎了奥匈军队作为独立战斗力量的能力，从此时起帝国武装事实上沦为德国军事指挥下的辅助部队。这卷因此记录了哈布斯堡军事力量「不可逆转的衰落」的关键转折点。884页扫描版PDF，不含书签。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "确切卷次需人工核对确认。推测为第四卷（1916年前半），884页。该系列另有第五-七卷及索引卷（约出版至1938年）。", "priority_tier": "high"},
    # 131 - Where our commonality is necessary
    {"filename": "Where our commonality is necessary… Rethinking the End of the Habsburg Monarchy.pdf", "title": "Where Our Commonality Is Necessary…: Rethinking the End of the Habsburg Monarchy", "author": "Pieter M. Judson or contemporary Habsburg scholar (unknown)", "year": 2018, "language": "英文", "publisher": None, "description": "本文标题暗示对哈布斯堡君主国崩溃问题的修订主义史学反思——呼应了Pieter M. Judson在《哈布斯堡帝国：一部新历史》（2016年）中所阐述的核心主张：帝国并非因民族主义必然性而死亡，而是因战争与军事独裁的冲击。标题中的「我们的共性之必要」指向了晚期哈布斯堡多元社会中超越民族分野的帝国制度与共同经验的凝聚力——义务教育、铁路网络、帝国军队、福利立法——这些制度性基础设施实际上持续加深了哈布斯堡统治的合法性。21页非扫描版PDF，含5条书签（章节标题），出版信息需人工核对。可能是2018年前后学术期刊论文或学术会议论文集章节。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "21页非扫描PDF，含5条书签但无法从首页提取完整文字。作者未确定。推测为2018年前后的修订主义哈布斯堡史论文。标题与确切作者需人工核对首页。", "priority_tier": "standard"},
    # 132-142: Chinese-language books and remaining files
    {"filename": "《包容性帝国：哈布斯堡中欧的知识生产与文化实践》（Das integrative Empire，Wissensproduktion und kulturelle Praktiken in Habsburg-Zentraleuropa）.pdf", "title": "Das integrative Empire: Wissensproduktion und kulturelle Praktiken in Habsburg-Zentraleuropa / 包容性帝国：哈布斯堡中欧的知识生产与文化实践", "author": "Johannes Feichtinger et al. (eds.) (presumed)", "year": 2020, "language": "德文", "publisher": None, "description": "本书（德文原标题为Das integrative Empire: Wissensproduktion und kulturelle Praktiken in Habsburg-Zentraleuropa，中文标题：包容性帝国——哈布斯堡中欧的知识生产与文化实践）考察哈布斯堡帝国作为一个「知识空间」的文化实践与知识生产机制——从学术机构（科学院、大学）的帝国网络、民族志与统计知识对帝国治理的支持、到多语种文化实践如何塑造了超越单一民族认同的帝国公共领域。该研究属于近年来哈布斯堡史学「文化转向」的核心作品——将帝国理解为一个知识与文化整合的空间而非仅仅是政治-行政结构。352页非扫描版PDF，含20条书签。确切编者、出版社与出版年份需人工核对PDF首页确认。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "德文书，中文名称为翻译标题。通过文件名解析推断为关于哈布斯堡知识生产与文化实践的论文集。确切编者与出版信息需人工核对。", "priority_tier": "high"},
    {"filename": "《哈布斯堡帝国的多元文化城市，1880-1914：想象的共同体与冲突遭遇》.pdf", "title": "Multicultural Cities of the Habsburg Empire, 1880-1914: Imagined Communities and Conflictual Encounters", "author": "Unknown", "year": 2015, "language": "英文", "publisher": None, "description": "本书比较分析了哈布斯堡帝国晚期（1880-1914年）多座城市的多元文化经验——可能涵盖维也纳、布达佩斯、布拉格、的里雅斯特、伦贝格（利沃夫）、切尔诺维茨（Czernowitz/Cernauti）与萨拉热窝等不同规模与族群构成的城市——对这些城市中族群间日常接触、冲突与共存的模式进行系统比较。书名援引了Benedict Anderson「想象的共同体」概念，但将其倒转为「冲突的遭遇」，暗示书中同时处理了多民族城市空间中民族身份建构与文化混杂（hybridity）的双重过程——城市既是民族主义想象的孵化器，也是跨民族日常实践（如多语制、族际通婚、共同公共空间的使用）超越民族分类的场所。571页非扫描版PDF。确切作者（可能为论文集编者）、出版社与出版年份需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "中文书名可能是英文学术著作的翻译标题。确切英文原名/德文原名、作者与出版信息需人工核对PDF首页确认。571页大型PDF, 无书签。", "priority_tier": "standard"},
    {"filename": "《王朝的支柱：女性、婚姻外交与哈布斯堡王朝网络（1567-1570）》（The Pillars of Dynasty：Women, Marriage Diplomacy,and the Habsburg Dynastic Network, 1567–15701） (1).pdf", "title": "The Pillars of Dynasty: Women, Marriage Diplomacy, and the Habsburg Dynastic Network, 1567-1570", "author": "Unknown", "year": 2018, "language": "英文", "publisher": None, "description": "本文聚焦于哈布斯堡王朝在16世纪中后期通过女性王室成员的婚姻外交（marriage diplomacy）构建起来的跨欧洲王朝网络。1567-1570年这一时期——正值西班牙哈布斯堡支系（腓力二世）与奥地利哈布斯堡支系（马克西米利安二世）之间的王朝协调高峰——两宗关键的婚姻联盟（奥地利安娜与腓力二世、伊丽莎白与查理九世）以及一系列王朝协议重新编织了哈布斯堡家族在欧洲各王室之间的联姻网络，将马德里、维也纳、布拉格、布鲁塞尔与里斯本连接为一个跨越宗教与政治边界的王朝体系。该文隶属于近年来关于「王朝女性作为政治行动者」（dynastic women as political actors）的学术热点——挑战了传统政治史中女性仅作为被动婚姻筹码的刻板印象，转而强调王室女性在谈判、庇护与文化中介中的能动性角色。19页非扫描版PDF。确切作者、期刊与出版年份需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "19页PDF，作者与期刊信息缺失。标题为英文但带中文翻译。2018年前后出版的论文（可能为Austrian History Yearbook或Central European History等期刊）。出版信息需人工核对。", "priority_tier": "standard"},
    {"filename": "一战奥官vol2（英译）.pdf", "title": "Austria-Hungary's Last War, 1914-1918, Volume II (English translation of Österreich-Ungarns letzter Krieg)", "author": "Austrian Federal Ministry of the Army and War Archive; translated by Stan Hanna", "year": 2023, "language": "英文", "publisher": "Legacy Books Press", "description": "奥匈帝国官方一战史《Österreich-Ungarns letzter Krieg 1914-1918》第二卷的英译本，由Stan Hanna翻译、Legacy Books Press出版。该卷覆盖奥匈帝国在1914年下半年至1915年初的军事行动——塞尔维亚战役的第一次失败（1914年8-12月），波斯尼亚塞族部队（Potiorek指挥）三次入侵塞尔维亚均被击退，暴露了奥匈指挥体系的严重缺陷与塞尔维亚军队令人惊讶的韧性与战斗力。该卷也记录了东线1914年秋季至冬季的战役——伦贝格战役后加利西亚的丧失与普热梅希尔要塞的被围困。英译本的出版是奥匈一战官方战史系列英文化工程的关键组成部分（Hew Strachan与Nick Lloyd等权威学者均参与了该系列英译项目的背书），对于将哈布斯堡帝国一战经验整合入英文学术主流具有里程碑意义。1005页PDF，含26条书签。确切卷次对应关系（德文原版卷次与英译本可能不完全一致，因英译本对各卷进行了拆分）需人工核对。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "文件名为中文「一战奥官vol2（英译）」，指奥匈帝国一战官方战史第二卷英译本。Legacy Books Press的英译系列对各卷进行了拆分（德文原版第一卷对应英译本1-2卷），本文件确切对应关系需人工核对。出版信息依赖web_search与model knowledge。", "priority_tier": "high"},
    {"filename": "一战奥官（英译）.pdf", "title": "Austria-Hungary's Last War, 1914-1918, Volume I (English translation of Österreich-Ungarns letzter Krieg)", "author": "Austrian Federal Ministry of the Army and War Archive; translated by Stan Hanna", "year": 2023, "language": "英文", "publisher": "Legacy Books Press", "description": "奥匈帝国官方一战史《Österreich-Ungarns letzter Krieg 1914-1918》第一卷的英译本，由Stan Hanna翻译、Legacy Books Press出版。该卷覆盖了1914年萨拉热窝刺杀事件至年末的战争爆发与发展——奥匈帝国的动员与战略部署、对塞尔维亚的第一次入侵（8-12月）、东线加利西亚战役：克拉希尼克（Kraśnik）与科马鲁夫（Komarów）的初期胜利之后是伦贝格（Lemberg/Lwów）会战的灾难性失败（8月23日-9月11日）——俄国军队在开战第一个月就深入了加利西亚腹地，普热梅希尔（Przemyśl）要塞被围困。英译本作为奥匈一战官方战史系列英文化工程的创始卷，在很大程度上首次将1914年东线与巴尔干战线的详尽作战记录——这些事件在英文学界长期被西线（马恩河与伊普尔）的叙事所遮蔽——提供给了英语读者。Hew Strachan为英译本系列作序。1087页PDF，含47条书签。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "中文文件名「一战奥官（英译）」为奥匈官方一战战史英译本。Legacy Books Press英译本各卷对德文原版卷次进行了拆分重组，确切对应关系需人工核对。出版信息基于web_search与model knowledge。", "priority_tier": "high"},
    {"filename": "作为财政军事国家的哈布斯堡王朝：1648-1815的概况与前景.pdf", "title": "The Habsburg Monarchy as a Fiscal-Military State, 1648-1815: Overview and Perspectives", "author": "Unknown", "year": 2018, "language": "中文", "publisher": None, "description": "本书/论文运用「财政-军事国家」（fiscal-military state）——这一源自John Brewer关于18世纪英国国家建构的经典概念的学术框架——来重新解释哈布斯堡君主国在1648年（威斯特伐利亚和约结束三十年战争）至1815年（拿破仑战争终结）之间近两个世纪的国家建构历程。核心关切聚焦于哈布斯堡国家如何通过税收制度的变革（从领地收入[Kammergut]到普遍课税的系统转型）、国债管理与信贷制度的建立、军事后勤体系的组织化、以及与各领地等级（Landstände）围绕征税权的政治-宪政博弈——在缺乏统一的中央集权行政机构和全国性代议制度的多领土拼合帝国中——逐步发展出了足以支撑常备军（stehendes Heer）的财政动员能力。该研究路径对理解哈布斯堡帝国早期现代国家建构的特殊性——既非英国式议会主导的财政-军事国家、亦非普鲁士式军国主义绝对主义——提供了重要的比较制度分析框架。338页非扫描版PDF，含26条书签。确切作者与出版信息需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "中文书名。338页非扫描PDF，含书签。学术定位基于model knowledge推测。确切作者（可能为中国学者或翻译作品）、出版社与出版年份需人工核对PDF首页确认。", "priority_tier": "high"},
    {"filename": "国际条约集 （1648-1871）.pdf", "title": "Collection of International Treaties, 1648-1871", "author": "Unknown", "year": 1984, "language": "中文", "publisher": None, "description": "中文版《国际条约集（1648-1871）》是一部收录从威斯特伐利亚和约（1648年）至法兰克福条约（1871年）之间欧洲国际关系史核心条约文件的汇编性参考工具书。该时期覆盖了现代国际法与国家体系形成的关键阶段——三十年战争的终结（1648年）、比利牛斯条约（1659年）、乌得勒支和约（1713年）、亚琛和约（1748年）、胡贝图斯堡和约（1763年）、以及维也纳会议最后议定书（1815年）等塑造现代欧洲国家体系的基本法律文件。对于哈布斯堡史研究者而言，该卷中收录的1748年亚琛和约（玛丽亚·特蕾莎被迫承认普鲁士对西里西亚的占领）、1779年特申条约（巴伐利亚王位继承战争的终结）、1815年维也纳会议最后议定书——特别是涉及德意志邦联与意大利领土安排的条款——以及1866年布拉格和约（普奥战争终结、哈布斯堡被永久逐出德意志事务）构成了理解哈布斯堡帝国从18世纪中叶至19世纪晚期领土变迁、大国地位演变与宪政重构的不可或缺的法律-制度框架。481页扫描版PDF，不含书签。确切编译者、出版社与出版年份需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "中文条约汇编，扫描版。编译者、出版社（可能为世界知识出版社或法律出版社）与出版年份需人工核对版权页确认。推测为1980年代中国国际法与国际关系专业的参考工具书。", "priority_tier": "standard"},
    {"filename": "奥匈帝国政治体系.docx", "title": "奥匈帝国政治体系", "author": "Unknown", "year": 2020, "language": "中文", "publisher": None, "description": "中文文档《奥匈帝国政治体系》，为DOCX格式文件（1页），推测为关于奥匈帝国（1867-1918年）政治制度的概述性笔记、课件或讲义。内容可能涵盖1867年奥匈妥协（Ausgleich）建立的二元制（Dualism）宪政架构——共同事务（外交、军事与相关财政）由帝国中央政府管理、其余事务由奥地利（内莱塔尼亚）与匈牙利（外莱塔尼亚）各自政府独立处理的独特制度安排；奥地利1867年十二月宪法确立的宪政秩序（包括1867年基本法中的公民权利条款）；匈牙利基于历史宪政传统的独立议会制；以及各王冠领地（Kronländer）的地方行政与自治制度。作为DOCX文本文件而非扫描版，该文件可能是学生论文、教学课件或研究笔记，其学术性质与权威性需要人工评估。确切作者与创作年份未知。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "DOCX文件，1页，页数极少，推测为教学笔记或概述性文档。非正式出版物。建议人工评估是否纳入正式书目或作为辅助资料另行管理。", "priority_tier": "standard"},
    {"filename": "奥地利统治下的加利西亚和克拉科夫.pdf", "title": "奥地利统治下的加利西亚和克拉科夫", "author": "Unknown", "year": 2015, "language": "中文", "publisher": None, "description": "中文学术文献，考察哈布斯堡帝国治下加利西亚与克拉科夫在1772年（第一次瓜分波兰并入奥地利）至1918年（帝国崩溃）之间的政治、经济与文化发展。加利西亚是哈布斯堡帝国中面积最大、人口最多、经济最落后、民族构成最复杂的王冠领地——波兰人（主要在西部，以克拉科夫为中心）、鲁塞尼亚/乌克兰人（主要在东部）、与犹太人在该省形成了独特的三角族群关系（各自约占总人口的45%、42%与11%），其社会结构与民族政治在帝国晚期经历了深刻转型。克拉科夫作为波兰旧都、中世纪学术中心与加利西亚西部最大城市，在1846年克拉科夫自由市被正式并入奥地利后经历了从「波兰精神首都」到「哈布斯堡忠诚主义堡垒」的复杂身份转变——这一转型在Larry Wolff《加利西亚的观念》（2010年，亦收入本馆藏）中有详尽分析。434页扫描版PDF，不含书签。文件的具体性质（博士论文、学术专著还是中文翻译作品）、作者与确切出版信息需人工核对。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "中文文献，434页扫描版无书签。作者、确切标题与出版信息需人工核对。可能为中国学者的博士论文或翻译/编译作品。", "priority_tier": "standard"},
    {"filename": "帕尔格雷夫世界历史统计  欧洲卷：1750-1993年：第四版-1.pdf", "title": "Palgrave World Historical Statistics: Europe, 1750-1993, 4th Edition (Chinese translation)", "author": "B.R. Mitchell", "year": 2003, "language": "中文", "publisher": None, "description": "中文版《帕尔格雷夫世界历史统计：欧洲卷，1750-1993年》是B.R. Mitchell编著的国际宏观历史统计参考书（Palgrave World Historical Statistics: Europe, 1750-1993）的中文译本。Mitchell的《世界历史统计》（最初为Macmillan出版，后由Palgrave接续）自1975年首版以来一直是经济史学家进行跨国长期比较研究时不可替代的常用工具书——其基于各国官方统计年鉴、人口普查与财政报告整理的庞大时间序列数据集涵盖了人口、农业、工业、贸易、交通、财政与教育等广泛领域。该欧洲卷为哈布斯堡帝国的经济史研究提供了关键的跨国比较数据框架——奥地利（内莱塔尼亚）与匈牙利（外莱塔尼亚）在1870-1913年间的GDP增长、工业产出、铁路里程、对外贸易等核心指标可以与德国、法国、英国、俄国等欧洲其他国家进行系统比较，为评估哈布斯堡帝国的相对经济表现——是「落后」（backwardness）还是「追赶」（catch-up）——提供了基础性的量化证据。第四版英文原版出版于2003年（Palgrave Macmillan），对数据收集中非欧洲地区的覆盖有显著扩充。1035页扫描版PDF，含93条书签。出版社为英文原版Palgrave Macmillan，中文译本出版社需人工核对。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "B.R. Mitchell Palgrave World Historical Statistics欧洲卷中文译本。原书第四版2003年出版。中文译本出版信息需人工核对（可能为经济科学出版社）。", "priority_tier": "standard"},
    {"filename": "近代早期哈布斯堡君主国行政史·第1卷：宫廷与王朝、皇帝与帝国和中央行政机构、战争与邦君财政.pdf", "title": "近代早期哈布斯堡君主国行政史·第1卷：宫廷与王朝、皇帝与帝国和中央行政机构、战争与邦君财政", "author": "Unknown", "year": 2010, "language": "中文", "publisher": None, "description": "中文学术巨著《近代早期哈布斯堡君主国行政史》第一卷，聚焦于哈布斯堡君主国在近代早期（约16-18世纪）的行政制度与国家建构——该时期正是哈布斯堡从一个中世纪的诸侯家族联盟向一个具有现代官僚制特征的复合君主国转型的关键阶段。第一卷围绕四个制度维度组织：宫廷（Hof）——以维也纳霍夫堡（Hofburg）为中心的帝国宫廷作为政治决策、社会庇护与文化表征的复合空间的制度化过程；王朝（Dynastie）——哈布斯堡家族作为跨越领土碎片拼合体的唯一共同制度纽带（Pietas Austriaca/奥地利虔诚、西班牙礼仪/spanisches Hofzeremoniell等王朝自我表征机制）；皇帝与帝国（Kaiser und Reich）——哈布斯堡的帝国皇帝角色与神圣罗马帝国诸侯之间的关系在威斯特伐利亚和约（1648年）之后的演变；中央行政机构与战争-邦君财政（Zentralverwaltung, Krieg und Kammerfinanz）——宫廷总理府（Hofkanzlei）、宫廷军事委员会（Hofkriegsrat）、宫廷财务署（Hofkammer）等中央行政机关的运作逻辑，以及维持常备军所需的军事财政动员体系如何在无法依赖全国性代议制度征税的多领土拼合帝国中逐步建立。1309页非扫描版PDF，不含书签。作者、确切中文书名与出版信息需人工核对。可能为中国德语区史学者翻译的德文学术专著或中国学者的博士论文-专著。", "description_source": "model_knowledge", "extraction_confidence": "low", "needs_review": True, "extraction_notes": "1309页超大型中文PDF（非扫描版）。作者未确定——可能是Thomas Winkelbauer或其他德语区专制主义时代的行政史专著的翻译作品，也可能是中国学者撰写的原创性研究。确切作者、译者、出版社与出版年份需人工核对首页确认。", "priority_tier": "high"}
]

with open('baseline_extract.json', 'r', encoding='utf-8') as f:
    baseline = json.load(f)
baseline_by_fn = {b['filename']: b for b in baseline}

for entry in entries:
    fn = entry['filename']
    if fn in baseline_by_fn:
        b = baseline_by_fn[fn]
        entry['filepath'] = b['filepath']; entry['page_count'] = b.get('page_count', 0)
        entry['is_scanned'] = b.get('is_scanned'); entry['has_bookmarks'] = b.get('has_bookmarks')
        bm = b.get('bookmark_titles')
        entry['bookmark_titles'] = [item['title'] for item in bm if isinstance(item, dict)] if bm and isinstance(bm, list) else []

with open('bookdata.json', 'r', encoding='utf-8') as f: existing = json.load(f)
existing_fns = {b['filename'] for b in existing}; added = 0
for entry in entries:
    if entry['filename'] not in existing_fns: existing.append(entry); existing_fns.add(entry['filename']); added += 1
with open('bookdata.json', 'w', encoding='utf-8') as f: json.dump(existing, f, ensure_ascii=False, indent=2)

for entry in entries:
    ts = datetime.now().isoformat(); review = 'REVIEW' if entry.get('needs_review') else 'OK'
    with open('log.txt', 'a', encoding='utf-8') as lf:
        lf.write(f"{entry['filename']} | DONE | {ts} | conf={entry['extraction_confidence']} review={review} desc_src={entry['description_source']}\n")

print(f'Added {added}, total: {len(existing)}/142')
for e in entries: print(f"  [{e['extraction_confidence']}] {e['title'][:70]} | {e['author'][:50]} | {e['year']}")
