"""Generate and write entries for books 91-100."""
import json, os
from datetime import datetime

entries = [
    {"filename": "The Habsburg Monarchy, 1618–1815 (Charles W. Ingrao) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Habsburg Monarchy, 1618-1815", "author": "Charles W. Ingrao", "year": 2000, "language": "英文", "publisher": "Cambridge University Press", "description": "Charles W. Ingrao（普渡大学历史学教授）的《哈布斯堡君主国，1618-1815》是剑桥大学出版社「欧洲史新路径」（New Approaches to European History）丛书中最受欢迎的卷册之一，初版1994年、第二版2000年（xiv+268页，附世系表与地图）。该书以清晰简洁的叙事覆盖了哈布斯堡帝国从三十年战争到拿破仑战争结束近两个世纪的早期现代史。Ingrao挑战了将哈布斯堡国家视为「落后」的传统观点，转而将其追溯为一个军事与文化强权的崛起历程。全书八章依次分析：奥地利历史的独特性、三十年战争（1618-1648）、面向东方——匈牙利与土耳其人（1648-1699）、面向西方——第二个哈布斯堡帝国与西班牙王位继承战争（1700-1740）、普鲁士的挑战——战争与政府改革（1740-1763）、发现人民——官房主义与开明专制的胜利（1765-1792）、革命时代（1789-1815）、衰落还是分解？第二版增设了新的尾声，考察哈布斯堡君主国对20世纪事件的影响，并更新了参考书目。该书作为大学本科哈布斯堡史课程的标准教科书被广泛使用，以对非专业读者友好的叙事风格与扎实的学术综合赢得了持续的影响力。2019年推出第三版。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。初版1994年、第二版2000年。本EPUB版本年份未能确定，默认填2000年。EPUB元数据需人工核对。", "priority_tier": "standard"},
    {"filename": "The Habsburg and Hohenzollern dynasties in the seventeenth and eighteenth centuries (Macartney, C. A. (Carlile Aylmer) etc.) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Habsburg and Hohenzollern Dynasties in the Seventeenth and Eighteenth Centuries", "author": "C.A. Macartney (editor)", "year": 1970, "language": "英文", "publisher": "Walker / Macmillan", "description": "C.A. Macartney编选的《17与18世纪的哈布斯堡与霍亨索伦王朝》是「西方文明文献史」（Documentary History of Western Civilization）丛书中的一卷，1970年由Walker（纽约）与Macmillan（伦敦）出版（vii+379页，附世系表）。这是一部文献史料汇编——而非Macartney本人的研究著作——收录了关于近代早期欧洲两大德意志王朝的精选一手史料英译本。全书以主题-时序结构组织，覆盖哈布斯堡王朝（奥地利史）与霍亨索伦王朝（普鲁士-德意志史）在17至18世纪的核心政治、宪法与外交文献，适合用作大学本科早期现代欧洲史课程的一手文献教材。Macartney（1895-1978）作为20世纪英语学界最权威的哈布斯堡与匈牙利史专家之一，其选文标准反映了传统的政治-宪法史视角，重点展示了「开明专制」（enlightened absolutism）范式下两大王朝的治理实践与制度建构。Harper & Row于同年发行平装本首版。作为文献汇编而非研究专著，该书的价值在于为研究者与非专业读者提供了直接接触玛丽亚·特蕾莎改革、约瑟夫二世谕令、普鲁士军事国家建构等关键历史进程之一手文本的便捷英译本通道。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Idea of Galicia History and Fantasy in Habsburg Political Culture (Larry Wolff) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Idea of Galicia: History and Fantasy in Habsburg Political Culture", "author": "Larry Wolff", "year": 2010, "language": "英文", "publisher": "Stanford University Press", "description": "Larry Wolff（纽约大学历史学教授）的《加利西亚的观念：哈布斯堡政治文化中的历史与幻想》是一部关于哈布斯堡帝国最东端王冠领地——加利西亚——的文化思想史杰作，2010年由斯坦福大学出版社出版（504页），2012年荣获奥地利联邦科学与研究部Karl von Vogelsang国家奖。Wolff延续其开创性著作《发明东欧》（Inventing Eastern Europe, 1994）的分析路径，将加利西亚视为「哈布斯堡王朝的字面发明」——1772年第一次瓜分波兰时人为划定的一个行政实体，其名称甚至是对中世纪加利西亚-沃里尼亚公国的虚构性援引——追踪了这一「观念」在帝国一个半世纪统治中如何在文学、民族志、政治话语与集体记忆中被不断建构、争论与重新想象。全书以10章的宏大结构从约瑟夫二世的启蒙规划（1770-1780年代）、梅特涅时代的复辟、萨克-马佐赫（Sacher-Masoch）的加利西亚童年与受虐狂概念的文化根源、1846年加利西亚农民大屠杀（rabacja）的持久创伤、自治时期（1867-1918）波兰效忠主义与Franz Joseph个人崇拜的政治运作、Karl Emil Franzos「半亚细亚」话语的东方主义逻辑、到二战后被波兰与苏联乌克兰分割以及21世纪「橙色革命」与学术怀旧中的加利西亚「来世」。Wolff的核心理念是：克拉科夫与伦贝格/利沃夫这两座城市共同生产了加利西亚的文化意义——加利西亚空间成为超越单一民族认同的多民族帝国想象的可能框架。Daniel Unowsky在H-Net赞誉其展现了「令人叹为观止的博学」。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Idea of Nation among the Romanians.pdf", "title": "The Idea of Nation: The Romanians of Transylvania, 1691-1849", "author": "Keith Hitchins", "year": 1985, "language": "英文", "publisher": "Editura Științifică și Enciclopedică (Bucharest)", "description": "Keith Hitchins的《民族观念：特兰西瓦尼亚的罗马尼亚人，1691-1849》是研究东欧民族认同形成史的重要学术著作，1985年由布加勒斯特科学出版社出版英文版（220页，后于1988年重印，1989年推出德文译本，1999年以《一个被发现民族》为题推出修订扩充版）。Hitchins聚焦于特兰西瓦尼亚——哈布斯堡帝国内罗马尼亚人口最集中、民族意识最早觉醒的区域——追踪从1691年（特兰西瓦尼亚正式归属哈布斯堡统治）至1848年革命期间罗马尼亚民族观念的形成过程。核心章节依次考察：与罗马的教会合一（东仪天主教会/Uniate Church的创立及其对罗马尼亚民族认同的关键催化作用）、族群民族的出现（Inochentie Klein主教作为早期民族觉醒的代表人物）、东正教与传统、图拉真的罗马与彼得与保罗的罗马——民族起源话语的二元建构、启蒙运动的影响、「民族崇拜」（cult of nationality）的思想形成、以及1848年革命作为民族运动政治成熟的关键时刻。全书以思想史（精英知识分子的民族话语生产）与社会史（教会制度、教育网络与阅读公众的形成）相结合的方法论为特色。该书是理解特兰西瓦尼亚罗马尼亚人如何在哈布斯堡帝国框架内——而非其外——发展出民族认同的关键文本。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "封面/首页未能提取以供验证。搜索显示此书最可能在1985年布加勒斯特初版（英文），1988年重印。文件名The Idea of Nation among the Romanians与已知书名The Idea of Nation: The Romanians of Transylvania, 1691-1849近似但不完全相同。建议人工核对封面确认完整书名与出版年份。", "priority_tier": "standard"},
    {"filename": "The Jews Of Vienna In The Age Of Franz Joseph (Robert S. Wistrich) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Jews of Vienna in the Age of Franz Joseph", "author": "Robert S. Wistrich", "year": 1989, "language": "英文", "publisher": "Oxford University Press (for the Littman Library of Jewish Civilization)", "description": "Robert S. Wistrich（1945-2015）的《弗朗茨·约瑟夫时代的维也纳犹太人》是维也纳犹太史领域最具权威性的综合巨著，1989年由牛津大学出版社为Littman犹太文明图书馆出版（xiv+696页，附图片）。Wistrich系希伯来大学现代犹太史教授、世界著名的反犹主义研究权威（其《反犹主义：最漫长的仇恨》为国际畅销书）。这部大型著作全景式地覆盖了维也纳犹太社群在弗朗茨·约瑟夫皇帝治下（1848-1916）的完整历史——从1867年宪法赋予犹太人完全法律平等到一战爆发前夕的半个世纪黄金时代——深入分析了人口迁移与城市化模式（至1910年维也纳犹太人口已达约17.5万，占城市总人口约8.6%）、职业结构的转型、居住区的社会地理学、文化适应（acculturation）与身份认同的复杂光谱（从正统派经自由派融入主义者到政治锡安主义者之间的内部张力）、反犹主义在市政政治（卡尔·卢埃格尔与基督教社会党）与泛日耳曼运动（舍内雷尔）中的政治动员、以及维也纳作为欧洲希伯来文学与现代犹太文化创造中心（从赫茨尔到弗洛伊德）的辉煌与悲剧。近700页的篇幅配以详尽的参考书目（pp. 667-679），该书是任何关于哈布斯堡晚期维也纳犹太社群研究不可或缺的参考文献。Wistrich于2015年去世，该书被誉为他的magnum opus。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Jews of Vienna and the First World War (David Rechter) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Jews of Vienna and the First World War", "author": "David Rechter", "year": 2001, "language": "英文", "publisher": "Littman Library of Jewish Civilization", "description": "David Rechter（牛津大学东方研究所与牛津希伯来与犹太研究中心教授）的《维也纳犹太人与第一次世界大战》是研究一战对中欧犹太社群冲击的重要专著，2001年由Littman犹太文明图书馆出版（xiii+218页）。Rechter以维也纳犹太社群在一战创伤年代的意识形态与身份认同危机为叙事主线，将其分析置于现代犹太政治的比较框架中——论证维也纳（及奥地利）犹太政治文化是东欧民族主义与激进主义同西欧自由主义的独特混合体。全书将维也纳犹太人划分为三个意识形态「阵营」：民族主义者（锡安主义者）、自由派融入主义者（同化派）与正统派。各章依次覆盖：一战前夕维也纳犹太社群的全景概述、涌入维也纳的加利西亚犹太难民（约15.7-38.5万人流经帝国首都）所引发的社群内部张力与社会危机、战时维也纳犹太青年运动的兴起、组织奥地利犹太人大会的尝试及其失败、以及战后锡安主义在意识形态竞争中作为「胜利者」崛起的过程。Rechter的核心史学论点是连续性——他论证战前的犹太意识形态在哈布斯堡君主国解体后惊人完整地存续下来，仍然植根于战前的假设之中，这一点与Marsha Rozenblit《重构民族认同》（亦收入本馆藏）所强调的「帝国崩溃触发了维也纳犹太人深刻的身份认同危机」的论点形成部分对话与张力。Ian Reifowitz在Shofar（2003年）中赞誉其档案研究「彻底且一流」。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Jews of Vienna, 1867-1914  assimilation and identity (Rozenblit, Marsha L., 1950-) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Jews of Vienna, 1867-1914: Assimilation and Identity", "author": "Marsha L. Rozenblit", "year": 1983, "language": "英文", "publisher": "State University of New York Press", "description": "Marsha L. Rozenblit（马里兰大学历史系教授）的《维也纳犹太人，1867-1914：同化与认同》是其关于哈布斯堡晚期维也纳犹太社群的代表性专著，1983年由SUNY出版社出版于「现代犹太史」丛书（xvii+284页，附插图、地图、表格与附录）。全书聚焦于1867年宪法赋予犹太人完全法律平等到一战爆发之间的关键半个世纪，系统分析了维也纳犹太社群如何将传统的、可识别的犹太行为模式转化为现代都市变体——而非抛弃其族群认同。核心章节依次考察：1867-1914年间向维也纳的犹太移民潮及其人口-社会结构特征（至1910年形成约17.5万人的欧洲最大德语犹太社群之一）、从传统小商人到现代白领职员的职业结构转型（「从贸易商到职员」）、维也纳犹太居住区的社会地理学——利奥波德城（Leopoldstadt）等犹太聚居区的形成与分化、中等教育（Gymnasium）作为社会流动与同化的核心制度通道的重要角色、异族通婚与改宗的社会学模式及统计趋势、组织网络（从宗教社区到B'nai B'rith到政治俱乐部）如何维系了犹太认同在都市化条件下的持续再生产、以及犹太民族主义者与同化主义者之间的「斗争」——这一内部意识形态之争如何塑造了维也纳犹太社群的公共政治文化。该书获美国历史评论（AHR, 1985年）书评，奠定了Rozenblit作为哈布斯堡犹太史领域权威学者的学术声誉。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Last years of Austria-Hungary  essays in political and military history, 1908-1918 (Cornwall, Mark) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Last Years of Austria-Hungary: Essays in Political and Military History, 1908-1918", "author": "Mark Cornwall (editor)", "year": 1990, "language": "英文", "publisher": "University of Exeter Press", "description": "Mark Cornwall（南安普顿大学东欧史教授、哈布斯堡帝国晚期史专家）主编的《奥匈帝国的最后岁月：政治与军事史论文集，1908-1918》是填补昂贵的教科书与专业研究专著之间空白的教学友好型论文集，1990年由埃克塞特大学出版社出版于「埃克塞特历史研究」丛书（No. 27，155页）。全书收录八篇专文，覆盖了哈布斯堡帝国最后二十年面临的政治、社会与国际挑战。核心议题包括：1908-1918年间君主国的外交政策演变、奥地利战前国内政治动态（从1907年普选改革到1914年战争爆发）、四次奥地利人口普查在政治生活中的独特角色（民族分类如何被政治化）、以及一战起因如何与哈布斯堡国家的结构性脆弱相交织。各篇论文分别由当时新一代的哈布斯堡史学者执笔，利用多语种档案材料为帝国持久力与最终崩溃提供了「新的见解与敏锐的提示」。Samuel R. Williamson在《国际史评论》中给予了积极评价。附有地图、扎实的参考书目与索引。后推出修订扩充版。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Lights that Failed European International History 1919-1933 (Zara Steiner) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Lights that Failed: European International History, 1919-1933", "author": "Zara Steiner", "year": 2005, "language": "英文", "publisher": "Oxford University Press", "description": "Zara Steiner（1928-2020，剑桥大学New Hall荣休研究员）的《熄灭的灯火：欧洲国际史，1919-1933》是牛津现代欧洲史系列中的里程碑式巨著，2005年出版（938页），代表了作者毕生的研究积累。该书是计划中的两卷本「两次大战之间欧洲国际史」的第一卷。Steiner系统地挑战了约翰·梅纳德·凯恩斯《和平的经济后果》（1919年）以来广泛接受的假设——凡尔赛条约自身就孕育着第二次世界大战的种子。她的核心论点是：1920年代应被视为一个「自成一体的战后时期」——而非仅仅是通向第二次全球冲突的令人沮丧的前奏——在这一时期政治家与外交官通过持续的适应性调整与实验，实现了一种虽然脆弱且不完整但确实是真实的稳定：在美国部分撤出欧洲与苏联自我约束不输出革命之间，一种可行的国际均势得以建立。决定性的断裂发生于1929-1933年这一「枢纽年份」——大萧条、满洲危机（1931年）与希特勒上台这三重冲击以毁灭性的方式改变了民族主义与国际主义之间的平衡。欧洲各大国与美国未能应对大萧条的后果——而非凡尔赛安排本身——应对魏玛共和国的崩溃与向独裁和战争的滑落承担首要责任。第一部分覆盖1918-1929年欧洲的重建（西欧与东欧和约缔造、苏联角色、经济重建、法西斯意大利、国际联盟、洛迦诺稳定及其局限），第二部分聚焦1929-1933年枢纽年份。附有详尽的统计附录、历任首相与外相名单、国际事件年表及广泛参考书目。Miklós Lojkó预言其「极有可能成为该领域的标准综述」。遗憾的是Steiner于2020年去世前未能完成其原定的第二卷《黑夜的胜利》。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Limits of Loyalty Imperial Symbolism, Popular Allegiances, and State Patriotism in the Late Habsburg Monarchy (Laurence Cole (editor) etc.) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Limits of Loyalty: Imperial Symbolism, Popular Allegiances, and State Patriotism in the Late Habsburg Monarchy", "author": "Laurence Cole and Daniel L. Unowsky (editors)", "year": 2007, "language": "英文", "publisher": "Berghahn Books", "description": "由Laurence Cole与Daniel L. Unowsky主编的《忠诚的限度：晚期哈布斯堡君主国的帝国象征、民众效忠与国家爱国主义》是第一部系统考察哈布斯堡帝国政府如何试图在多民族语境中生成一种「以王朝为导向的国家爱国主义」的学术论文集，2007年由Berghahn Books出版于「奥地利与哈布斯堡研究」丛书（第9卷，viii+246页）。该论文集的核心学术贡献在于将分析视角从民族运动与族群冲突——长期以来主导晚期哈布斯堡史学的焦点——转向了国家与统治王朝：帝国的制度与象征体系在凝聚臣民方面是否——以及在多大程度上——取得了成功？各章由当时新一代哈布斯堡史学者执笔，覆盖了教育作为帝国爱国主义生产场所（Ernst Bruckmüller论小学教育中的爱国与民族神话）、军事退伍军人协会与民间爱国主义（Laurence Cole）、约瑟夫二世的帝国想象延续至1914年（Nancy Wingfield）、弗朗茨·约瑟夫个人崇拜与捷克民众忠诚的张力（Hugh Agnew）、1880年波兰人与鲁塞尼亚人围绕皇帝巡游展开的民族代表权公共竞争（Unowsky）、伊丽莎白皇后（茜茜公主）在匈牙利的「名人君主制」崇拜（Alice Freifeld）、克罗地亚学生抗议与仪式性戏仿所揭示的忠诚限度（Sarah Kent）、以及R.J.W. Evans撰写的结论。全书论证的一个核心洞察是：民族意识的增长与王朝忠诚并非相互排斥——甚至可能呈正相关关系——民族主义活动家往往将王朝象征挪用于自己的目的，而非简单地拒绝帝国框架本身。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。Berghahn Books 2007年出版。EPUB元数据需人工核对。", "priority_tier": "standard"}
]

with open('baseline_extract.json', 'r', encoding='utf-8') as f:
    baseline = json.load(f)
baseline_by_fn = {b['filename']: b for b in baseline}

for entry in entries:
    fn = entry['filename']
    if fn in baseline_by_fn:
        b = baseline_by_fn[fn]
        entry['filepath'] = b['filepath']; entry['page_count'] = b.get('page_count', 0)
        entry['is_scanned'] = b.get('is_scanned'); entry['has_bookmarks'] = b.get('has_bookmarks')
        bm = b.get('bookmark_titles')
        entry['bookmark_titles'] = [item['title'] for item in bm if isinstance(item, dict)] if bm and isinstance(bm, list) else []

with open('bookdata.json', 'r', encoding='utf-8') as f: existing = json.load(f)
existing_fns = {b['filename'] for b in existing}; added = 0
for entry in entries:
    if entry['filename'] not in existing_fns: existing.append(entry); existing_fns.add(entry['filename']); added += 1
with open('bookdata.json', 'w', encoding='utf-8') as f: json.dump(existing, f, ensure_ascii=False, indent=2)

for entry in entries:
    ts = datetime.now().isoformat(); review = 'REVIEW' if entry.get('needs_review') else 'OK'
    with open('log.txt', 'a', encoding='utf-8') as lf:
        lf.write(f"{entry['filename']} | DONE | {ts} | conf={entry['extraction_confidence']} review={review} desc_src={entry['description_source']}\n")

print(f'Added {added}, total: {len(existing)}/142')
for e in entries: print(f"  [{e['extraction_confidence']}] {e['title'][:70]} | {e['author'][:50]} | {e['year']}")
