"""Generate and write entries for books 101-110."""
import json, os
from datetime import datetime

entries = [
    {"filename": "The Military Border in Croatia, 1740-1881 a Study of an Imperial Institution (Gunther Erich Rothenberg) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Military Border in Croatia, 1740-1881: A Study of an Imperial Institution", "author": "Gunther E. Rothenberg", "year": 1966, "language": "英文", "publisher": "University of Chicago Press", "description": "Gunther E. Rothenberg的《克罗地亚的军事边疆，1740-1881：一项帝国制度研究》是研究哈布斯堡军事边疆（Militärgrenze）这一独特帝国制度的最权威英文专著，1966年由芝加哥大学出版社出版（224页，附折叠地图）。军事边疆是哈布斯堡帝国在克罗地亚-斯拉沃尼亚与奥斯曼帝国边界沿线设立的军事化行政区域——这片土地上居住着拥有免于封建义务、以服兵役换取土地的自由农民-士兵（Grenzer/边疆人），构成了欧洲历史上最持久的军事殖民制度之一。Rothenberg系统分析了这一制度从1740年玛丽亚·特蕾莎治下的重组到1881年完全非军事化（demilitarization）并被并入克罗地亚-斯拉沃尼亚民事管辖的完整演变——涵盖了其军事组织、土地占有制、族群构成（以塞尔维亚东正教移民与克罗地亚天主教徒为主）、与维也纳宫廷及匈牙利议会之间复杂的政治-法律三角关系、以及19世纪民族主义时代作为「塞尔维亚民族意识摇篮」与「克罗地亚国家权利象征」的双重象征角色。该书与其续篇《弗朗茨·约瑟夫的军队》（亦收入本馆藏）共同构成Rothenberg关于哈布斯堡军事制度的两卷本经典，附有详尽参考书目（pp. 197-214）。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Multinational Empire. Nationalism and National Reform in the Habsburg Monarchy 1848-1918. Volume I. Empire and… (Kann, Robert) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Multinational Empire: Nationalism and National Reform in the Habsburg Monarchy, 1848-1918. Volume I: Empire and Nationalities", "author": "Robert A. Kann", "year": 1950, "language": "英文", "publisher": "Columbia University Press", "description": "Robert A. Kann（1906-1981，罗格斯大学历史学教授）的《多民族帝国：哈布斯堡君主国的民族主义与民族改革，1848-1918》是20世纪中期美国哈布斯堡史学的奠基性巨著，1950年由哥伦比亚大学出版社出版两卷本（Vol. I: xxi+444页，Vol. II: xiv+423页，定价$12.50）。本馆藏为第一卷「帝国与诸民族」。Kann在维也纳大学获法学博士学位后于1938年纳粹吞并奥地利后流亡美国，其流亡学者的双重法学-史学背景深刻塑造了本书的分析框架——将哈布斯堡帝国的民族问题既作为历史实证研究又作为政治理论的比较个案来处理。第一卷系统剖析了帝国境内十一大民族群体（德意志人、马扎尔人、捷克人、斯洛伐克人、波兰人、鲁塞尼亚/乌克兰人、斯洛文尼亚人、克罗地亚人、塞尔维亚人、罗马尼亚人与意大利人）的历史发展、人口地理、社会结构与政治诉求，特别关注了奥地利犹太人（尤其是加利西亚与布科维纳的犹太社群）的独特地位。详尽的书目注释（pp. 346-444）构成了早期哈布斯堡民族问题研究的不可或缺的文献指南。美国历史评论（AHR, 1951年4月）称其为「过去十年美国对多瑙帝国近期历史所做出的显著众多的贡献中最值得注意的著作之一」。Octagon Books于1977年推出重印版。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Multinational Empire. Nationalism and National Reform in the Habsburg Monarchy 1848-1918. Volume II. Empire Reform (Kann, Robert) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Multinational Empire: Nationalism and National Reform in the Habsburg Monarchy, 1848-1918. Volume II: Empire Reform", "author": "Robert A. Kann", "year": 1950, "language": "英文", "publisher": "Columbia University Press", "description": "Robert A. Kann的《多民族帝国》第二卷「帝国改革」聚焦于哈布斯堡帝国晚期围绕民族问题展开的宪法与政治改革方案——从1848年克雷姆西尔议会（Kremsier Reichstag）的宪法草案到1918年帝国解体前夕的最后改革尝试——系统分析了逾半打以上的重大改革提案与思想流派。Kann对每一种方案（从联邦主义[federalism]到自治主义[autonomism]到中央集权主义[centralism]及其各种混合变体）的理论基础、可行性、支持者与反对者进行了详尽剖析，尤其对奥雷尔·波波维奇（Aurel Popovici）的「大奥地利合众国」方案（1906年）与卡尔·伦纳（Karl Renner）及奥托·鲍威尔（Otto Bauer）的奥地利马克思主义民族文化自治理论给予了特别深入的学术关注。第二卷也是Kann在哥伦比亚大学的博士论文基础，附有注释（pp. 319-372）与选择性参考书目（pp. 375-380）。作为研究多民族帝国如何在制度上回应民族主义挑战的比较政治学经典，Kann的两卷本虽在档案利用与理论框架上已被后辈学者（如Judson的修订主义叙事）所超越，但其学术史地位无可替代——它奠定了此后两代哈布斯堡民族问题研究的分析范畴与问题意识。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Nation in the Village The Genesis of Peasant National Identity in Austrian Poland, 1848–1914 (Keely Stauter-Halsted) (z-library.sk, 1lib.sk, z-lib.sk).epub", "title": "The Nation in the Village: The Genesis of Peasant National Identity in Austrian Poland, 1848-1914", "author": "Keely Stauter-Halsted", "year": 2001, "language": "英文", "publisher": "Cornell University Press", "description": "Keely Stauter-Halsted的《村庄中的民族：奥地利波兰农民民族认同的起源，1848-1914》是研究哈布斯堡晚期加利西亚底层社会史与民族主义建构的获奖著作，2001年由康奈尔大学出版社出版（x+272页）。该书从根本上挑战了民族主义研究的「涓滴模型」（trickle-down model）——即民族情感自上而下从知识分子与城市中产阶级渗透至广大农民——转而论证波兰农民在民族认同的生成过程中做出了独立的、积极的贡献。Stauter-Halsted创造性地将哈贝马斯「公共领域」（public sphere）概念延伸到乡村语境：她揭示1848年农奴制废除后加利西亚乡村社会如何发展出一种「农村公民社会」——从村议会与酒馆中的政治辩论、农业圈协会（1882年起）、乡村报刊、到学校教师在传播虔诚、爱国主义与识字教育中的关键中介角色——通过这些正式与非正式的民主讨论空间，农民逐步将自身定义为「道德、清醒、虔诚与勤奋的民族中坚」，与「腐败、都市化、不忠诚」的贵族阶级相对立。全书的另一核心洞见是反犹主义在民族建构中的功能性作用——将精英与农民团结在民族主义议程背后的跨阶级整合工具。2005年科希丘什科起义百年纪念等历史纪念活动及农村出版物的兴起构成了传播「道德-民族愿景」的关键载体。该书以对华沙、克拉科夫与利沃夫档案的跨学科研究为基础，被广泛赞誉为民族主义研究与东欧农民政治史交叉领域中的「富有洞见与创新性的贡献」。", "description_source": "web_search", "extraction_confidence": "medium", "needs_review": True, "extraction_notes": "EPUB文件，ebooklib提取失败。Cornell University Press 2001年出版。EPUB元数据需人工核对。", "priority_tier": "standard"},
    {"filename": "The Origins of the War in 1914 Vol.1 (Luigi Albertini) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Origins of the War of 1914, Volume I: European Relations from the Congress of Berlin to the Eve of the Sarajevo Murder", "author": "Luigi Albertini; translated and edited by Isabella M. Massey", "year": 1952, "language": "英文", "publisher": "Oxford University Press", "description": "Luigi Albertini（1871-1941）的《1914年大战的起源》是关于第一次世界大战起源最详尽、最权威的多卷本研究著作，英文译本由Isabella M. Massey翻译与编辑，牛津大学出版社出版（1952-1957年，三卷本总计逾2100页）。Albertini系意大利著名记者、参议员与《晚邮报》（Corriere della Sera）前主编，因反法西斯立场在墨索里尼治下被逐出新闻界后倾其余生投入这部巨著的撰写——1941年去世时未能见其出版（意大利文原版Le Origini della Guerra del 1914于1945年由米兰Bocca出版社出版）。第一卷（612页）覆盖从1878年柏林会议到1914年萨拉热窝刺杀前夕的欧洲外交关系——系统分析俾斯麦同盟体系的构建、德国外交政策在威廉二世与比洛治下的转向、「三国同盟」与「三国协约」之间的极化、1908-1909年波斯尼亚兼并危机与1912-1913年巴尔干战争的外交后果、以及意大利在地中海外交中的独特角色。Albertini对德国政策持严厉批判立场，对「旧外交」制度及其以秘密条约与军事承诺取代公众问责的运作逻辑进行了深刻的自由派-民主派批评。该书尤以对地中海与意大利外交的详尽处理——这是英美学界其他一战起源通论中常被忽略的维度——而著称。Enigma Books于2005年推出更新版重印。三卷本至今仍是专业一战史学者不可绕过的核心参考文献。本馆藏全三卷均收录。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Origins of the War in 1914 Vol.2 (Luigi Albertini) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Origins of the War of 1914, Volume II: The Crisis of July 1914 — From the Sarajevo Outrage to the Austro-Hungarian General Mobilization", "author": "Luigi Albertini; translated and edited by Isabella M. Massey", "year": 1952, "language": "英文", "publisher": "Oxford University Press", "description": "Luigi Albertini《1914年大战的起源》第二卷（727页）聚焦于历史上最著名的外交危机——1914年七月危机——从6月28日萨拉热窝刺杀到7月31日奥匈帝国总动员的外交决策过程。Albertini以逐日、有时甚至逐小时的叙事密度，重建了维也纳、柏林、圣彼得堡、巴黎与伦敦各国外交部与军事决策圈内的互动博弈。该卷的核心分析贡献在于对「霍约斯使命」（7月5日亚历山大·霍约斯伯爵赴柏林获取德国「空白支票」的秘密外交行动）及其决定性后果的详尽档案重建、对贝希托尔德外相在奥匈帝国内部政治-军事决策中的核心角色的评估、以及对各国外交官员个人性格、意识形态预判与信息不对称如何结构性驱动了整个七月危机升级过程的微观分析。Albertini在意大利外交（特别是圣朱利亚诺外相的中立立场与意大利在三国同盟框架内的摇摆策略）方面提供了英美学界无可比拟的处理深度——这得益于其意大利记者的身份背景与对意大利档案的独特接触。该卷至今仍是关于七月危机外交决策过程的最详尽、最权威的单卷叙述之一，与第一卷共同构成Albertini巨著的核心学术贡献。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Origins of the War in 1914 Vol.3 (Luigi Albertini) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Origins of the War of 1914, Volume III: The Epilogue of the Crisis of July 1914 — The Declarations of War and of Neutrality", "author": "Luigi Albertini; translated and edited by Isabella M. Massey", "year": 1957, "language": "英文", "publisher": "Oxford University Press", "description": "Luigi Albertini《1914年大战的起源》第三卷（772页）覆盖七月危机的终章——从1914年7月31日至8月初各交战国的宣战与中立国立场的确立——以及作者对整个危机过程的史学反思与对战争责任的最终判断。该卷逐日追踪了从德国对俄宣战（8月1日）、入侵比利时及英国参战（8月4日）、到意大利宣布中立——尽管是三国同盟的正式成员国（1914年8月3日）——的外交终局。Albertini详细分析了比利时中立问题在英国参战决策中的关键作用、格雷（Edward Grey）外交大臣在伦敦协调调停努力的失败原因、以及德国总参谋部「施里芬计划」的军事时间表逻辑如何覆写了最后时刻外交解决的可能性。在结论部分，Albertini提出了其影响深远的战争责任分配判断——他严厉批评德国在七月危机中的不负责任行为，但同时拒绝将全部责任归于任何单一国家，而是将批评矛头指向整个欧洲外交体系的结构性缺陷与各国决策层在危机管理中的集体失败。第三卷的篇幅（772页）几乎是第一、二卷的总和，反映了作者对危机终章外交法理与道德问题的哲学式关注——作为一位被法西斯政权政治放逐的前记者与参议员，Albertini关于公众问责与外交民主化必要性的自由主义信念在该卷中得到了最充分的表达。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Politics of Backwardness in Hungary, 1825-1945 (Andrew C. Janos) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Politics of Backwardness in Hungary, 1825-1945", "author": "Andrew C. Janos", "year": 1982, "language": "英文", "publisher": "Princeton University Press", "description": "Andrew C. Janos的《匈牙利的落后政治，1825-1945》是东欧比较政治学与依附理论的经典著作，1982年由普林斯顿大学出版社出版（xxxvi+370页，附地图）。Janos（加州大学伯克利分校政治学教授）以一个挑衅性的核心问题为起点：为什么匈牙利——一个与西欧共享大量宗教与制度遗产的国家——未能在19世纪与20世纪早期复制西欧的社会与政治经验？他的答案挑战了文化与「国民性」解释，转而指向现代世界体系的内部动力——匈牙利的边缘（peripheral）经济地位在国内产生了无法在本国落后经济框架内实现的现代化愿望，形成了一种结构性的「落后陷阱」。全书依次追踪了这一陷阱在一个多世纪中的制度表现：自由主义制度从西方的移植尝试（1825-1848）、西方模式的自由主义制度如何被腐蚀为一种「新社团主义」官僚国家（1849-1905）、左翼革命（1906-1919）、新社团主义的复辟（1919-1931）、以及右翼革命（1932-1945）。Janos将匈牙利的经验与当代第三世界国家的困境建立了系统性类比，使得该书不仅对东欧政治专家具有吸引力，也成为发展研究、依附理论与中心-边缘关系领域的必读文献。Foreign Affairs（1982年）赞誉该书作为匈牙利的政治社会史「非常成功」，在将其置于欧洲与全球变迁的广阔视野方面「始终刺激」。2012年由普林斯顿大学出版社重印电子书版（Princeton Legacy Library）。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "high"},
    {"filename": "The Pomp and Politics of Patriotism Imperial Celebrations in Habsburg Austria, 1848-1916 (Daniel L. Unowsky) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Pomp and Politics of Patriotism: Imperial Celebrations in Habsburg Austria, 1848-1916", "author": "Daniel L. Unowsky", "year": 2005, "language": "英文", "publisher": "Purdue University Press", "description": "Daniel L. Unowsky（孟菲斯大学中欧与东欧史副教授）的《爱国主义的盛典与政治：哈布斯堡奥地利的帝国庆典，1848-1916》是第一部系统研究哈布斯堡帝国如何在仪式层面建构国家爱国主义的专著，2005年由普渡大学出版社出版于「中欧研究」丛书（xiii+263页），源于作者在哥伦比亚大学István Deák指导下的博士论文（2000年）。全书聚焦于弗朗茨·约瑟夫皇帝的公共形象如何被王朝政府作为「构建力量」来培育一种超民族的奥地利国家爱国主义——在民族主义运动高涨的时代中提供替代性的帝国认同框架。各章依次考察：1848年革命后宫廷仪式的复兴与公共庆典的发明（基督圣体节游行与濯足节洗脚礼等传统的再创造与再神圣化）；皇帝对加利西亚的巡游（1851年的Kaiserreise、被取消的1868年巡游计划、以及1880与1894年访问）如何展现了宫廷对各地政治条件的适应；1898年盛大禧年的官方信息传播、朝廷对皇帝公共形象的控制在日益壮大的公民社会中逐渐丧失、以及基督教社会党等政党如何将帝国形象挪用于自身政治目的；以及1908年登基60周年庆典的简短处理。Unowsky的核心论点是：现代化与政治参与的扩大虽增加了控制皇帝公共形象的难度，但帝国庆典恰恰使不同民族、政党与声音能够——以各自的方式——宣示对王朝以及一个「想象中奥地利共同体」的忠诚，体现了超民族认同与民族认同在一个政治参与扩张时代的复杂张力。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Resurrection and Collapse of Empire in Habsburg Serbia, 1914-1918 (Jonathan E. Gumz) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Resurrection and Collapse of Empire in Habsburg Serbia, 1914-1918", "author": "Jonathan E. Gumz", "year": 2009, "language": "英文", "publisher": "Cambridge University Press", "description": "Jonathan E. Gumz的《哈布斯堡塞尔维亚的帝国复苏与崩溃，1914-1918》是剑桥军事史丛书中的一部突破性著作，2009年出版（xii+275页，附插图，后于2013年发行平装本）。本书通过细致分析哈布斯堡军队在1914-1918年间对塞尔维亚的军事占领，提出了一个挑战一战史学主流范式的核心论点：与20世纪其他殖民计划或军事占领截然不同，这一占领「沿着一条明显以欧洲为中心的轨道运行」——哈布斯堡军队并非追求种族压迫或殖民剥削，而是试图「去民族化与去政治化」塞尔维亚社会，逐步减少占领暴力的强度，并最终将该国完全融入帝国体系。这些目标植根于19世纪的保守主义与君主制信念——这一意识形态框架强制军队在广泛的法律与「文明」约束下运作，与同期德国在东欧推行的、受种族主义与达尔文主义世界观驱动的极端占领政策形成了尖锐对比。各章依次分析了哈布斯堡军队1914年面对塞尔维亚「全民皆兵」（levée en masse）时的反应、在占领区铲除民族政治的努力、军事司法体系的运作（从「法律严厉性」到其最终崩溃）、食品供应作为巩固帝国统治的工具与象征、以及反游击战争的经验。该书深刻修正了将一战简单等同于「全面战争」与种族化暴力的标准叙事，为理解晚期哈布斯堡帝国的政治-军事文化提供了全新视角。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"},
    {"filename": "The Road to Sarajevo (1966) (Vladimir Dedijer) (z-library.sk, 1lib.sk, z-lib.sk).pdf", "title": "The Road to Sarajevo", "author": "Vladimir Dedijer", "year": 1966, "language": "英文", "publisher": "Simon and Schuster", "description": "Vladimir Dedijer（1914-1990）的《通往萨拉热窝之路》是关于1914年6月28日弗朗茨·斐迪南大公遇刺事件最详尽的英文叙事史之一，1966年由Simon & Schuster出版（纽约，550页，附黑白照片与彩色地图）。Dedijer系南斯拉夫历史学家与政治人物——二战期间为铁托的游击队员、战后曾任南斯拉夫出席联合国代表团成员——后因与铁托政权的分歧转向独立学术研究，先后在多所英美大学任教。这部著作远超一般的刺杀叙事：Dedijer将刺杀事件深深嵌入19世纪南斯拉夫民族革命运动（特别是「青年波斯尼亚」/Mlada Bosna的激进学生-革命家网络）的社会与思想史背景之中，同时提供了对弗朗茨·斐迪南大公——这位被历史遗忘的复杂性人物（非简单的保守反动派，而是兼具改革思想与专制倾向的悲剧角色）——的性格、政治理念与家庭生活的深度心理传记分析。Dedijer利用了大量此前未被使用的南斯拉夫警方与法庭档案、暗杀者的书信与审讯记录、以及对大公身边人士的采访，为萨拉热窝事件提供了前所未有的微观史学细节。尽管其亲南斯拉夫立场与偶尔过度强调「青年波斯尼亚」作为理想主义自由斗士的浪漫化处理受到部分学术批评，该书至今仍是研究一战爆发前夕南斯拉夫民族革命运动与哈布斯堡帝国晚期政治危机的最重要英文参考文献之一。", "description_source": "web_search", "extraction_confidence": "high", "needs_review": False, "extraction_notes": "", "priority_tier": "standard"}
]

with open('baseline_extract.json', 'r', encoding='utf-8') as f: baseline = json.load(f)
baseline_by_fn = {b['filename']: b for b in baseline}
for entry in entries:
    fn = entry['filename']
    if fn in baseline_by_fn:
        b = baseline_by_fn[fn]
        entry['filepath'] = b['filepath']; entry['page_count'] = b.get('page_count', 0)
        entry['is_scanned'] = b.get('is_scanned'); entry['has_bookmarks'] = b.get('has_bookmarks')
        bm = b.get('bookmark_titles')
        entry['bookmark_titles'] = [item['title'] for item in bm if isinstance(item, dict)] if bm and isinstance(bm, list) else []

with open('bookdata.json', 'r', encoding='utf-8') as f: existing = json.load(f)
existing_fns = {b['filename'] for b in existing}; added = 0
for entry in entries:
    if entry['filename'] not in existing_fns: existing.append(entry); existing_fns.add(entry['filename']); added += 1
with open('bookdata.json', 'w', encoding='utf-8') as f: json.dump(existing, f, ensure_ascii=False, indent=2)

for entry in entries:
    ts = datetime.now().isoformat(); review = 'REVIEW' if entry.get('needs_review') else 'OK'
    with open('log.txt', 'a', encoding='utf-8') as lf:
        lf.write(f"{entry['filename']} | DONE | {ts} | conf={entry['extraction_confidence']} review={review} desc_src={entry['description_source']}\n")

print(f'Added {added}, total: {len(existing)}/142')
for e in entries: print(f"  [{e['extraction_confidence']}] {e['title'][:70]} | {e['author'][:50]} | {e['year']}")
